/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.foodrive.Volunteer;

import project.foodrive.Monitor.*;
import project.foodrive.Admin.*;
import Testing.*;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.border.Border;
import javax.swing.BorderFactory;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.border.EtchedBorder;
import project.foodrive.MyConnection;
import project.foodrive.Volunteer.Notification_panel;
import project.foodrive.Volunteer.Notification_record_panel;

/**
 *
 * @author abcd
 */
public class Drive_volunteer_RecordPanel extends javax.swing.JPanel {

    /**
     * Creates new form recordPanel
     */
    private int member_id=-1;
    private int area_id=-1;
    private int drive_id=-1;
    private int monitor_id=-1;
    Volunteer_dashboard mainFrame;
    private String drive_status="";
    
    
    public Drive_volunteer_RecordPanel() {
        initComponents();
    }
    
    public Drive_volunteer_RecordPanel(int memberid,int areaid,int driveid,Volunteer_dashboard obj) {
        initComponents();
        member_id=memberid;
        area_id=areaid;
        drive_id=driveid;
        mainFrame=obj;
        multi_purpose_btn.setText("");
        multi_purpose_btn.setOpaque(false);
        multi_purpose_btn.setEnabled(false);
        load_details();
    }
    
    private Color recordPanMouseEnterColor = new Color(220,220,220);
    private Color recordPanMouseExitColor = new Color(255,255,255);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        id = new javax.swing.JLabel();
        status_text = new javax.swing.JLabel();
        start_time_text = new javax.swing.JLabel();
        viewDetailsIcon = new javax.swing.JLabel();
        max_vol_text = new javax.swing.JLabel();
        multi_purpose_btn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(790, 40));
        setMinimumSize(new java.awt.Dimension(790, 40));
        setPreferredSize(new java.awt.Dimension(790, 40));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        id.setBackground(new java.awt.Color(255, 255, 255));
        id.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        id.setText("<id>");

        status_text.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        status_text.setText("status");

        start_time_text.setBackground(new java.awt.Color(204, 204, 204));
        start_time_text.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        start_time_text.setText("Start_time");

        viewDetailsIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewDetailsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/details-small.png"))); // NOI18N
        viewDetailsIcon.setAlignmentY(1.0F);
        viewDetailsIcon.setMaximumSize(new java.awt.Dimension(40, 40));
        viewDetailsIcon.setMinimumSize(new java.awt.Dimension(40, 40));
        viewDetailsIcon.setPreferredSize(new java.awt.Dimension(40, 40));
        viewDetailsIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewDetailsIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewDetailsIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewDetailsIconMouseExited(evt);
            }
        });

        max_vol_text.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        max_vol_text.setText("max_volunteer");
        max_vol_text.setPreferredSize(new java.awt.Dimension(50, 18));

        multi_purpose_btn.setBackground(new java.awt.Color(102, 102, 255));
        multi_purpose_btn.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        multi_purpose_btn.setForeground(new java.awt.Color(255, 255, 255));
        multi_purpose_btn.setText("I'm In");
        multi_purpose_btn.setContentAreaFilled(false);
        multi_purpose_btn.setOpaque(true);
        multi_purpose_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multi_purpose_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(status_text, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(start_time_text, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(max_vol_text, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(multi_purpose_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(viewDetailsIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(viewDetailsIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(status_text)
                            .addComponent(start_time_text)
                            .addComponent(max_vol_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(multi_purpose_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
        this.setBackground(recordPanMouseEnterColor);
        Border raisedBevelBorder = BorderFactory.createRaisedBevelBorder();
        this.setBorder(raisedBevelBorder);
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        // TODO add your handling code here:
        this.setBackground(recordPanMouseExitColor);
        Border raisedEtchedBorder = new EtchedBorder(EtchedBorder.RAISED);
        this.setBorder(raisedEtchedBorder);
    }//GEN-LAST:event_formMouseExited

    private void viewDetailsIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewDetailsIconMouseEntered
        // TODO add your handling code here:
        Border raisedBevelBorder = BorderFactory.createRaisedBevelBorder();
        this.viewDetailsIcon.setBorder(raisedBevelBorder); 
        formMouseEntered(evt);
    }//GEN-LAST:event_viewDetailsIconMouseEntered

    private void viewDetailsIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewDetailsIconMouseExited
        // TODO add your handling code here:
        this.viewDetailsIcon.setBorder(BorderFactory.createEmptyBorder());
        formMouseExited(evt);
    }//GEN-LAST:event_viewDetailsIconMouseExited

    private void viewDetailsIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewDetailsIconMouseClicked
        // TODO add your handling code here:
        Drive_details_frame vol_frame=new Drive_details_frame(member_id,drive_id,area_id);
        vol_frame.setVisible(true);
        
        //mainFrame.setFocusableWindowState(false);
        //JDialog dialog=new JDialog(vol_frame, "Volunteer Details", true);
        //dialog.setVisible(true);
    }//GEN-LAST:event_viewDetailsIconMouseClicked

    private void multi_purpose_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multi_purpose_btnActionPerformed
        // TODO add your handling code here:
        Connection c=null;
        MyConnection mo= new MyConnection();
        c=mo.getMyConnection();
        if(multi_purpose_btn.getText().equals("I'm In")){
            int optionSelected=JOptionPane.showConfirmDialog(null, "Want to attend Drive?...\nAre you sure?", "Warning..!", JOptionPane.YES_NO_OPTION);
            if(optionSelected==JOptionPane.YES_OPTION){
            try {
                String query="INSERT INTO attendance (member_id, drive_id, datetime, attendance_flag, monitor_id) VALUES (?, ?, NOW(), 1, ?);";
                
                PreparedStatement pst=c.prepareStatement(query);
                pst.setInt(1, member_id);
                pst.setInt(2, drive_id);
                pst.setInt(3, monitor_id);
                pst.executeUpdate();
                multi_purpose_btn.setText("You'r In");
                multi_purpose_btn.setOpaque(true);
                multi_purpose_btn.setEnabled(false);
            } catch (SQLException ex) {
                Logger.getLogger(Drive_RecordPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
        }
    }//GEN-LAST:event_multi_purpose_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel id;
    private javax.swing.JLabel max_vol_text;
    private javax.swing.JButton multi_purpose_btn;
    private javax.swing.JLabel start_time_text;
    private javax.swing.JLabel status_text;
    private javax.swing.JLabel viewDetailsIcon;
    // End of variables declaration//GEN-END:variables

    private void load_details() {
        try {
            Connection c=null;
            MyConnection mo= new MyConnection();
            c=mo.getMyConnection();
            
            String query="SELECT * FROM drive WHERE drive_id=?;";
            
            PreparedStatement pst=c.prepareStatement(query);
            pst.setInt(1, drive_id);
            
            ResultSet rs=pst.executeQuery();
            
            while(rs.next()){
                monitor_id=rs.getInt("monitor_id");
                this.id.setText(""+rs.getInt("drive_id"));
                this.status_text.setText(rs.getString("status"));
                drive_status=rs.getString("status");
                this.start_time_text.setText(rs.getString("start_time"));
                if(rs.getString("max_volunteers")==null)
                {
                    this.max_vol_text.setText("-");
                }
                else{
                    this.max_vol_text.setText(rs.getString("max_volunteers"));
                }
                if(drive_status.equals("Needy_Circle_Confirmed"))
                {
                    String query2="SELECT COUNT(*) as count FROM attendance WHERE drive_id=? AND member_id=?;";
            
                    PreparedStatement pst2=c.prepareStatement(query2);
                    pst2.setInt(1, drive_id);
                    pst2.setInt(2, member_id);
                    int atte_count=0;
                    ResultSet rs2=pst2.executeQuery();
                    if(rs.next()){
                        atte_count=rs.getInt("count");
                    }
                    if(atte_count==0){
                        multi_purpose_btn.setText("I'm In");
                        multi_purpose_btn.setOpaque(true);
                        multi_purpose_btn.setEnabled(true);
                    }
                    else{
                        multi_purpose_btn.setText("You'r In");
                        multi_purpose_btn.setOpaque(true);
                        multi_purpose_btn.setEnabled(false);
                        
                    }
                }
                
               
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Notification_panel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
}
