/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.foodrive.Volunteer;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import project.foodrive.MyConnection;

/**
 *
 * @author INTEL COREi3
 */
public class Notification_panel extends javax.swing.JPanel {

    /**
     * Creates new form Notification_panel
     */
    private int member_id=-1;
    private int area_id=-1;
    public Notification_panel() {
        initComponents();
    }
    
    public Notification_panel(int memberid,int areaid) {
        initComponents();
        member_id=memberid;
        area_id=areaid;
        load_notification();
    }
    
    public void load_notification(){
        try {
            Connection c=null;
            MyConnection mo= new MyConnection();
            c=mo.getMyConnection();
            
            String query="SELECT n.notification_id FROM notification n JOIN member m ON m.member_id=n.receiver_ref_id"
                    + " WHERE ((n.receiver_ref_id=? AND n.type='volunteer')"
                    + " OR (n.receiver_ref_id=? AND n.type='area')) AND n.indatetime>=m.joindate ORDER BY n.indatetime DESC;";
            
            PreparedStatement pst=c.prepareStatement(query);
            pst.setInt(1, member_id);
            pst.setInt(2, area_id);
            
            ResultSet rs=pst.executeQuery();
            main_notification_panel.removeAll();
            while(rs.next()){
                
                main_notification_panel.add(new Notification_record_panel(rs.getInt("notification_id")));
                main_notification_panel.revalidate();
                main_notification_panel.repaint();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Notification_panel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    JPanel main_load_Panel_voldash;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        main_notification_panel = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(850, 550));
        setMinimumSize(new java.awt.Dimension(850, 550));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        main_notification_panel.setMaximumSize(new java.awt.Dimension(522, 516));
        main_notification_panel.setMinimumSize(new java.awt.Dimension(522, 516));
        main_notification_panel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                main_notification_panelComponentShown(evt);
            }
        });
        main_notification_panel.setLayout(new javax.swing.BoxLayout(main_notification_panel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(main_notification_panel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void main_notification_panelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_main_notification_panelComponentShown
        // TODO add your handling code here:
        main_notification_panel.add(new Notification_record_panel());
        main_notification_panel.add(new Notification_record_panel());
        main_notification_panel.add(new Notification_record_panel());
        main_notification_panel.revalidate();
        main_notification_panel.repaint();
    }//GEN-LAST:event_main_notification_panelComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel main_notification_panel;
    // End of variables declaration//GEN-END:variables
}
