/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.foodrive.Volunteer;

import project.foodrive.Donor.*;
import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import project.foodrive.MyConnection;
import project.foodrive.Volunteer.Notification_panel;
import project.foodrive.Volunteer.Notification_record_panel;

/**
 *
 * @author INTEL COREi3
 */
public class Volunteer_profile_view extends javax.swing.JPanel {

    /**
     * Creates new form Donor_profile_view
     */
    private int member_id=-1;
    public Volunteer_profile_view(){
        initComponents();
         
        
    }
    public Volunteer_profile_view(int memberid){
         initComponents();
       member_id=memberid;
      
      load_volunteer();
    }
    private void load_volunteer(){
        
        try {
            
            System.out.println("here 0");
            Connection c=null;
            MyConnection mo= new MyConnection();
            c=mo.getMyConnection();
            System.out.println("connected");
          String query="SELECT member.member_id,member.fname,member.lname,member.email,member.phone,member.alternate_phone,member.dob,member.gender,member.points,member.joindate,volunteer.type,area.area_id,area.area_name,area.city,area.state,area.country FROM ((member INNER JOIN volunteer ON member.member_id=volunteer.member_id) INNER JOIN area ON area.area_id=volunteer.area_id) WHERE member.member_id=?;";
            
            System.out.println(query);
            PreparedStatement pst=c.prepareStatement(query);
            System.out.println(member_id);
            pst.setInt(1,member_id);
            ResultSet rs=pst.executeQuery();
             
            while(rs.next()){
                System.out.println("here in rs");
               //this.get_mid.setText(""+rs.getInt("member_id"));
                System.out.println(rs.getString("email"));
                String email=rs.getString("email");
               //get_email.setText(rs.getString("email"));
               get_email.setText(email);
               this.get_phone.setText(rs.getString("phone"));
               this.get_alt_phone.setText(rs.getString("alternate_phone"));
               this.get_type.setText(rs.getString("type")); 
               this.get_dob1.setText(rs.getString("dob"));
               this.get_gender.setText(rs.getString("gender"));
               this.get_points.setText(""+rs.getInt("points"));
               this.get_join_date.setText(rs.getString("joindate"));
               
               this.get_areaname.setText(rs.getString("area_name"));
               this.get_city.setText(rs.getString("city"));
               this.get_state.setText(rs.getString("state"));
               this.get_country.setText(rs.getString("country"));
               this.get_area_id.setText(""+rs.getInt("area_id"));
               this.get_name.setText(rs.getString("fname")+" "+rs.getString("lname"));
              
            }
            c.close();
        } catch (SQLException ex) {
            Logger.getLogger(Notification_panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profile = new javax.swing.JLabel();
        get_name = new javax.swing.JLabel();
        personal_details = new javax.swing.JPanel();
        email_label = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        get_mid = new javax.swing.JLabel();
        get_type = new javax.swing.JLabel();
        get_email = new javax.swing.JLabel();
        phonne_label = new javax.swing.JLabel();
        get_phone = new javax.swing.JLabel();
        alt_phone_label = new javax.swing.JLabel();
        get_alt_phone = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        get_gender = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        get_dob1 = new javax.swing.JLabel();
        points_label = new javax.swing.JLabel();
        get_points = new javax.swing.JLabel();
        points_label1 = new javax.swing.JLabel();
        get_join_date = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        get_areaname = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        get_country = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        get_state = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        get_city = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        get_area_id = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(850, 550));
        setMinimumSize(new java.awt.Dimension(850, 550));
        setPreferredSize(new java.awt.Dimension(850, 550));

        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        profile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        get_name.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        get_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        get_name.setText("Name");
        get_name.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        personal_details.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Personal Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 14))); // NOI18N
        personal_details.setPreferredSize(new java.awt.Dimension(541, 190));

        email_label.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        email_label.setText("Email ");

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel13.setText("Type");

        get_mid.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_mid.setText("1");

        get_type.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_type.setText("*type*");

        get_email.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_email.setText("*email*");

        phonne_label.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        phonne_label.setText("Phone");

        get_phone.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_phone.setText("*number*");

        alt_phone_label.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        alt_phone_label.setText("Alternate Phone ");

        get_alt_phone.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_alt_phone.setText("*number*");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setText("Member_id");

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel14.setText("DOB");

        get_gender.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_gender.setText("*dob*");

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel15.setText("Gender");

        get_dob1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_dob1.setText("*dob*");

        points_label.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        points_label.setText("Points");

        get_points.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_points.setText("*points*");

        points_label1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        points_label1.setText("Join_date");

        get_join_date.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_join_date.setText("*date*");

        javax.swing.GroupLayout personal_detailsLayout = new javax.swing.GroupLayout(personal_details);
        personal_details.setLayout(personal_detailsLayout);
        personal_detailsLayout.setHorizontalGroup(
            personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personal_detailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personal_detailsLayout.createSequentialGroup()
                        .addGroup(personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alt_phone_label)
                            .addComponent(jLabel4)
                            .addComponent(email_label)
                            .addComponent(phonne_label))
                        .addGroup(personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personal_detailsLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(get_mid, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(get_email)
                                    .addComponent(get_phone)))
                            .addGroup(personal_detailsLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(get_alt_phone)))
                        .addGap(48, 48, 48)
                        .addGroup(personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(points_label1)
                            .addComponent(points_label)
                            .addComponent(jLabel15)
                            .addComponent(jLabel13))
                        .addGap(64, 64, 64)
                        .addGroup(personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(get_type)
                            .addComponent(get_gender)
                            .addComponent(get_points)
                            .addComponent(get_join_date)))
                    .addComponent(jLabel14)
                    .addGroup(personal_detailsLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(get_dob1)))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        personal_detailsLayout.setVerticalGroup(
            personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personal_detailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personal_detailsLayout.createSequentialGroup()
                        .addGroup(personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(get_mid)
                            .addComponent(jLabel15)
                            .addComponent(get_gender))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(get_email)
                            .addComponent(points_label)
                            .addComponent(get_points))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(get_join_date)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(get_type))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personal_detailsLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(email_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phonne_label)
                            .addComponent(get_phone)
                            .addComponent(points_label1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(alt_phone_label)
                            .addComponent(get_alt_phone)
                            .addComponent(jLabel13))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(get_dob1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Address Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 14)))); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(539, 161));

        get_areaname.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_areaname.setText("Gujrath Colony");

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("Area Name");

        get_country.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_country.setText("India");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("Country");

        get_state.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_state.setText("jLabel10");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("State");

        get_city.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_city.setText("jLabel11");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setText("City");

        get_area_id.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_area_id.setText("jLabel12");

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setText("Area_id");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(get_areaname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(get_country, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(get_state, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(get_city, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(get_area_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(get_areaname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(get_country))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(get_state))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(get_city))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(get_area_id))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(get_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(profile)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(personal_details, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profile)
                .addComponent(get_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(personal_details, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alt_phone_label;
    private javax.swing.JLabel email_label;
    private javax.swing.JLabel get_alt_phone;
    private javax.swing.JLabel get_area_id;
    private javax.swing.JLabel get_areaname;
    private javax.swing.JLabel get_city;
    private javax.swing.JLabel get_country;
    private javax.swing.JLabel get_dob1;
    private javax.swing.JLabel get_email;
    private javax.swing.JLabel get_gender;
    private javax.swing.JLabel get_join_date;
    private javax.swing.JLabel get_mid;
    private javax.swing.JLabel get_name;
    private javax.swing.JLabel get_phone;
    private javax.swing.JLabel get_points;
    private javax.swing.JLabel get_state;
    private javax.swing.JLabel get_type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel personal_details;
    private javax.swing.JLabel phonne_label;
    private javax.swing.JLabel points_label;
    private javax.swing.JLabel points_label1;
    private javax.swing.JLabel profile;
    // End of variables declaration//GEN-END:variables
}
