/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.foodrive.Volunteer;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import project.foodrive.Admin.Admin_donor_view;
import project.foodrive.Admin.Admin_volunteer_view;
import project.foodrive.GetStarted_Final;
import project.foodrive.Monitor.Monitor_Notification_panel;
import project.foodrive.MyConnection;

/**
 *
 * @author INTEL COREi3
 */
public class Volunteer_dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Volunteer_dashboard
     */
    private int member_id=-1;
    private int area_id=-1;
    
    
    public Volunteer_dashboard() {
        initComponents();
    }
    
    public Volunteer_dashboard(int memberid,int areaid) {
        initComponents();
        member_id=memberid;
        area_id=areaid;
        load_details_in_header();
      
        
        System.out.println(member_id+" "+area_id);
    }
    private Color mouseExitedColor = new Color(21, 95, 48);
    private Color mouseEnteredColor = new Color(0,23,0);
    private Color mouseClickedColor = new Color(21,143,21);
    private Color passiveFontColor = new Color(204,204,204);
    private Color activeFontColor = new Color(255,255,255);
    private int selected_option_from_left=0;
    
    private void setAllOptionAsNonSelected(){
        profile_pan.setBackground(mouseExitedColor);
        volunteer_label.setForeground(passiveFontColor);
        drive_pan.setBackground(mouseExitedColor);
        donor_label.setForeground(passiveFontColor);
        chapter_pan.setBackground(mouseExitedColor);
        chapter_label.setForeground(passiveFontColor);
        monitor_pan.setBackground(mouseExitedColor);
        monitor_label.setForeground(passiveFontColor);
        
    }
    
     private void load_details_in_header(){
        try {
            Connection c=null;
            MyConnection mo= new MyConnection();
            c=mo.getMyConnection();
            //get volunteer req count
            String query="SELECT fname,lname FROM member WHERE member_id=?; ";
            
            PreparedStatement pst=c.prepareStatement(query);
            pst.setInt(1, member_id);
            ResultSet rs=pst.executeQuery();
            
            if(rs.next()){
                String volunteer_name=rs.getString("fname")+" "+rs.getString("lname");
                volunteer_name_lab.setText(volunteer_name);
            }
            
            c.close();
            //join_count.setText(""+count);
        } catch (SQLException ex) {
            Logger.getLogger(Monitor_Notification_panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel_voldash = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        volunteer_name_lab = new javax.swing.JLabel();
        notification_btn = new javax.swing.JLabel();
        logout_btn = new javax.swing.JLabel();
        leftPanel_voldash = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        profile_pan = new javax.swing.JPanel();
        volunteer_label = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        drive_pan = new javax.swing.JPanel();
        donor_label = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        chapter_pan = new javax.swing.JPanel();
        chapter_label = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        monitor_pan = new javax.swing.JPanel();
        monitor_label = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        main_load_Panel_voldash = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 600));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        headerPanel_voldash.setBackground(new java.awt.Color(21, 95, 48));

        jLabel8.setFont(new java.awt.Font("Segoe Marker", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Volunteer");

        volunteer_name_lab.setFont(new java.awt.Font("Segoe Marker", 0, 20)); // NOI18N
        volunteer_name_lab.setForeground(new java.awt.Color(255, 255, 255));
        volunteer_name_lab.setText("Monitor_Name");

        notification_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        notification_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/notification.png"))); // NOI18N
        notification_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                notification_btnMouseClicked(evt);
            }
        });

        logout_btn.setForeground(new java.awt.Color(255, 255, 255));
        logout_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout_small.png"))); // NOI18N
        logout_btn.setText("Logout");
        logout_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_btnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout headerPanel_voldashLayout = new javax.swing.GroupLayout(headerPanel_voldash);
        headerPanel_voldash.setLayout(headerPanel_voldashLayout);
        headerPanel_voldashLayout.setHorizontalGroup(
            headerPanel_voldashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanel_voldashLayout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(volunteer_name_lab, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(notification_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logout_btn)
                .addGap(18, 18, 18))
        );
        headerPanel_voldashLayout.setVerticalGroup(
            headerPanel_voldashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(notification_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanel_voldashLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(headerPanel_voldashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanel_voldashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(volunteer_name_lab)
                        .addComponent(jLabel8))
                    .addComponent(logout_btn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        leftPanel_voldash.setBackground(new java.awt.Color(21, 95, 48));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_gr_bg_medium.PNG"))); // NOI18N

        profile_pan.setBackground(new java.awt.Color(21, 95, 48));
        profile_pan.setMaximumSize(new java.awt.Dimension(250, 45));
        profile_pan.setMinimumSize(new java.awt.Dimension(250, 45));
        profile_pan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profile_panMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profile_panMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profile_panMouseExited(evt);
            }
        });

        volunteer_label.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        volunteer_label.setForeground(new java.awt.Color(204, 204, 204));
        volunteer_label.setText("Profile");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/volunteer_icon.png"))); // NOI18N

        javax.swing.GroupLayout profile_panLayout = new javax.swing.GroupLayout(profile_pan);
        profile_pan.setLayout(profile_panLayout);
        profile_panLayout.setHorizontalGroup(
            profile_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profile_panLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(volunteer_label)
                .addContainerGap(128, Short.MAX_VALUE))
        );
        profile_panLayout.setVerticalGroup(
            profile_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profile_panLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(profile_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(volunteer_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        drive_pan.setBackground(new java.awt.Color(21, 95, 48));
        drive_pan.setMaximumSize(new java.awt.Dimension(250, 45));
        drive_pan.setMinimumSize(new java.awt.Dimension(250, 45));
        drive_pan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                drive_panMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                drive_panMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                drive_panMouseExited(evt);
            }
        });

        donor_label.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        donor_label.setForeground(new java.awt.Color(204, 204, 204));
        donor_label.setText("Drive");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/donate_icon.png"))); // NOI18N

        javax.swing.GroupLayout drive_panLayout = new javax.swing.GroupLayout(drive_pan);
        drive_pan.setLayout(drive_panLayout);
        drive_panLayout.setHorizontalGroup(
            drive_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drive_panLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(donor_label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        drive_panLayout.setVerticalGroup(
            drive_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drive_panLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(drive_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(donor_label))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        chapter_pan.setBackground(new java.awt.Color(21, 95, 48));
        chapter_pan.setMaximumSize(new java.awt.Dimension(250, 45));
        chapter_pan.setMinimumSize(new java.awt.Dimension(250, 45));
        chapter_pan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chapter_panMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                chapter_panMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                chapter_panMouseExited(evt);
            }
        });

        chapter_label.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        chapter_label.setForeground(new java.awt.Color(204, 204, 204));
        chapter_label.setText("Chapter");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/location_icon.png"))); // NOI18N

        javax.swing.GroupLayout chapter_panLayout = new javax.swing.GroupLayout(chapter_pan);
        chapter_pan.setLayout(chapter_panLayout);
        chapter_panLayout.setHorizontalGroup(
            chapter_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chapter_panLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(chapter_label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        chapter_panLayout.setVerticalGroup(
            chapter_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chapter_panLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(chapter_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(chapter_label))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        monitor_pan.setBackground(new java.awt.Color(21, 95, 48));
        monitor_pan.setMaximumSize(new java.awt.Dimension(250, 45));
        monitor_pan.setMinimumSize(new java.awt.Dimension(250, 45));
        monitor_pan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                monitor_panMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                monitor_panMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                monitor_panMouseExited(evt);
            }
        });

        monitor_label.setBackground(new java.awt.Color(204, 204, 204));
        monitor_label.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        monitor_label.setForeground(new java.awt.Color(204, 204, 204));
        monitor_label.setText("Monitor");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/monitor_icon.png"))); // NOI18N

        javax.swing.GroupLayout monitor_panLayout = new javax.swing.GroupLayout(monitor_pan);
        monitor_pan.setLayout(monitor_panLayout);
        monitor_panLayout.setHorizontalGroup(
            monitor_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(monitor_panLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(monitor_label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        monitor_panLayout.setVerticalGroup(
            monitor_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, monitor_panLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(monitor_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(monitor_label))
                .addContainerGap())
        );

        javax.swing.GroupLayout leftPanel_voldashLayout = new javax.swing.GroupLayout(leftPanel_voldash);
        leftPanel_voldash.setLayout(leftPanel_voldashLayout);
        leftPanel_voldashLayout.setHorizontalGroup(
            leftPanel_voldashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanel_voldashLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(leftPanel_voldashLayout.createSequentialGroup()
                .addGroup(leftPanel_voldashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(chapter_pan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(monitor_pan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(drive_pan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(profile_pan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        leftPanel_voldashLayout.setVerticalGroup(
            leftPanel_voldashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanel_voldashLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addComponent(profile_pan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(drive_pan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(chapter_pan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(monitor_pan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        main_load_Panel_voldash.setToolTipText("");
        main_load_Panel_voldash.setMaximumSize(new java.awt.Dimension(850, 550));
        main_load_Panel_voldash.setMinimumSize(new java.awt.Dimension(850, 550));
        main_load_Panel_voldash.setPreferredSize(new java.awt.Dimension(850, 550));
        main_load_Panel_voldash.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(leftPanel_voldash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headerPanel_voldash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(main_load_Panel_voldash, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel_voldash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(main_load_Panel_voldash, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(leftPanel_voldash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1126, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void monitor_panMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monitor_panMouseExited
        // TODO add your handling code here:
        
        if(selected_option_from_left!=4)
        {
            monitor_pan.setBackground(mouseExitedColor);
            monitor_label.setForeground(passiveFontColor);
        }
    }//GEN-LAST:event_monitor_panMouseExited

    private void monitor_panMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monitor_panMouseEntered
           // TODO add your handling code here:
            
        if(selected_option_from_left!=4)
        {
            monitor_pan.setBackground(mouseEnteredColor);
            monitor_label.setForeground(activeFontColor);
        }
    }//GEN-LAST:event_monitor_panMouseEntered

    private void monitor_panMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monitor_panMouseClicked
        // TODO add your handling code here:
         
        setAllOptionAsNonSelected();
        monitor_pan.setBackground(mouseClickedColor);
        monitor_label.setForeground(activeFontColor);
        selected_option_from_left=4;
    }//GEN-LAST:event_monitor_panMouseClicked

    private void chapter_panMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chapter_panMouseExited
        // TODO add your handling code here:
        if(selected_option_from_left!=3)
        {
            chapter_pan.setBackground(mouseExitedColor);
            chapter_label.setForeground(passiveFontColor);
        }
    }//GEN-LAST:event_chapter_panMouseExited

    private void chapter_panMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chapter_panMouseEntered
        // TODO add your handling code here:
        if(selected_option_from_left!=3)
        {
            chapter_pan.setBackground(mouseEnteredColor);
            chapter_label.setForeground(activeFontColor);
        }
    }//GEN-LAST:event_chapter_panMouseEntered

    private void chapter_panMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chapter_panMouseClicked
        // TODO add your handling code here:
        setAllOptionAsNonSelected();
        chapter_pan.setBackground(mouseClickedColor);
        chapter_label.setForeground(activeFontColor);
        selected_option_from_left=3;
          main_load_Panel_voldash.removeAll();
        main_load_Panel_voldash.add(new Volunteer_Chapter_view(area_id,this),BorderLayout.CENTER);
        main_load_Panel_voldash.revalidate();
        main_load_Panel_voldash.repaint();
    }//GEN-LAST:event_chapter_panMouseClicked

    private void drive_panMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drive_panMouseExited
        // TODO add your handling code here:
        if(selected_option_from_left!=2)
        {
            drive_pan.setBackground(mouseExitedColor);
            donor_label.setForeground(passiveFontColor);
        }
    }//GEN-LAST:event_drive_panMouseExited

    private void drive_panMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drive_panMouseEntered
        // TODO add your handling code here:
        if(selected_option_from_left!=2)
        {
            drive_pan.setBackground(mouseEnteredColor);
            donor_label.setForeground(activeFontColor);
        }
    }//GEN-LAST:event_drive_panMouseEntered

    private void drive_panMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drive_panMouseClicked
        // TODO add your handling code here:
        setAllOptionAsNonSelected();
        drive_pan.setBackground(mouseClickedColor);
        donor_label.setForeground(activeFontColor);
        selected_option_from_left=2;

        main_load_Panel_voldash.removeAll();
        main_load_Panel_voldash.add(new Drive_volunteer_status_view(member_id, area_id,this),BorderLayout.CENTER);
        main_load_Panel_voldash.revalidate();
        main_load_Panel_voldash.repaint();
        
    }//GEN-LAST:event_drive_panMouseClicked

    private void profile_panMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profile_panMouseExited
        // TODO add your handling code here:
        
        if(selected_option_from_left!=1)
        {
            profile_pan.setBackground(mouseExitedColor);
            volunteer_label.setForeground(passiveFontColor);
        }
    }//GEN-LAST:event_profile_panMouseExited

    private void profile_panMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profile_panMouseEntered
        // TODO add your handling code here:
        

        if(selected_option_from_left!=1)
        {
            profile_pan.setBackground(mouseEnteredColor);
            volunteer_label.setForeground(activeFontColor);
        }
    }//GEN-LAST:event_profile_panMouseEntered

    private void profile_panMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profile_panMouseClicked
        setAllOptionAsNonSelected();
        profile_pan.setBackground(mouseClickedColor);
        volunteer_label.setForeground(activeFontColor);
        selected_option_from_left=1;

        main_load_Panel_voldash.removeAll();
        main_load_Panel_voldash.add(new Volunteer_profile_view(member_id),BorderLayout.CENTER);
        main_load_Panel_voldash.revalidate();
        main_load_Panel_voldash.repaint();
       
    }//GEN-LAST:event_profile_panMouseClicked

    private void notification_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notification_btnMouseClicked
        // TODO add your handling code here:
        main_load_Panel_voldash.removeAll();
        main_load_Panel_voldash.add(new Notification_panel(member_id,area_id),BorderLayout.CENTER);
        main_load_Panel_voldash.repaint();
        main_load_Panel_voldash.revalidate();
    }//GEN-LAST:event_notification_btnMouseClicked

    private void logout_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_btnMouseClicked
        // TODO add your handling code here:
        GetStarted_Final getStarted_Final=new GetStarted_Final();
        getStarted_Final.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logout_btnMouseClicked
 public void load_in_main_panel(Component panel){
        main_load_Panel_voldash.removeAll();
        main_load_Panel_voldash.add(panel,BorderLayout.CENTER);
        main_load_Panel_voldash.revalidate();
        main_load_Panel_voldash.repaint();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Volunteer_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Volunteer_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Volunteer_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Volunteer_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Volunteer_dashboard(1,1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chapter_label;
    private javax.swing.JPanel chapter_pan;
    private javax.swing.JLabel donor_label;
    private javax.swing.JPanel drive_pan;
    private javax.swing.JPanel headerPanel_voldash;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel leftPanel_voldash;
    private javax.swing.JLabel logout_btn;
    private javax.swing.JPanel main_load_Panel_voldash;
    private javax.swing.JLabel monitor_label;
    private javax.swing.JPanel monitor_pan;
    private javax.swing.JLabel notification_btn;
    private javax.swing.JPanel profile_pan;
    private javax.swing.JLabel volunteer_label;
    private javax.swing.JLabel volunteer_name_lab;
    // End of variables declaration//GEN-END:variables
}
