/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.foodrive;

import Testing.*;
import java.awt.Color;
import java.awt.Component;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author INTEL COREi3
 */
public class joinus_donor extends javax.swing.JFrame {
    
    private int validate_all=7;
    public joinus_donor() {
        initComponents();
         load_cities();
        
    }
     public int getAreaId(Connection c){
        try {
            Statement s=c.createStatement();
            String select_area_id="SELECT area_id FROM area "
                    + "WHERE country='"+country_cb.getSelectedItem().toString()+"' "
                    + "AND state = '"+state_cb.getSelectedItem().toString()+"'"
                    + "AND city = '"+city_cb.getSelectedItem().toString()+"'"
                    + "AND area_name = '"+area_cb.getSelectedItem().toString()+"';";
            ResultSet rs=s.executeQuery(select_area_id);
            rs.next();
            int area_id=rs.getInt("area_id");
            return area_id;
        } catch (SQLException ex) {
            Logger.getLogger(Joinus.class.getName()).log(Level.SEVERE, null, ex);
        }
        return 0;
    }
     public void load_cities(){
        try {
            Connection c=null;
            MyConnection mo= new MyConnection(); 
            c=mo.getMyConnection();
            //Connect Database Block
            
            Statement st = c.createStatement();
            String s = "SELECT DISTINCT country FROM area;";
            ResultSet rs = st.executeQuery(s);
            while(rs.next()){
                country_cb.addItem(rs.getString("country"));
                
            }
            country_cb.setSelectedItem("India");
            state_cb.setSelectedItem("Maharashtra");
            city_cb.setSelectedItem("Pune");
            
        } catch (SQLException ex) {
            Logger.getLogger(Joinus.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private boolean check_regex(String regex,String inpuString){
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(inpuString);
        if(matcher.matches()){
            return true;
        }
        else{
            return false;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        dname_label = new javax.swing.JLabel();
        dname_text = new javax.swing.JTextField();
        dtype_label = new javax.swing.JLabel();
        dphone_label = new javax.swing.JLabel();
        d_phone_text = new javax.swing.JTextField();
        dalt_phone_label = new javax.swing.JLabel();
        dalt_phone_text = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Title_label = new javax.swing.JLabel();
        add_donor = new javax.swing.JButton();
        cancel_donor = new javax.swing.JButton();
        dtype_combobox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        demail_text = new javax.swing.JTextField();
        city_cb = new javax.swing.JComboBox<>();
        state_cb = new javax.swing.JComboBox<>();
        country_cb = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        emaill_label1 = new javax.swing.JLabel();
        emaill_label2 = new javax.swing.JLabel();
        emaill_label3 = new javax.swing.JLabel();
        area_cb = new javax.swing.JComboBox<>();
        emaill_label4 = new javax.swing.JLabel();
        uname_text = new javax.swing.JTextField();
        alt_phone_label1 = new javax.swing.JLabel();
        alt_phone_label2 = new javax.swing.JLabel();
        alt_phone_label3 = new javax.swing.JLabel();
        pass_text = new javax.swing.JPasswordField();
        pass_retype_text = new javax.swing.JPasswordField();
        error_msg_bottom_lb = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        address_text = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(850, 550));
        setResizable(false);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setMaximumSize(new java.awt.Dimension(850, 550));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(850, 550));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(850, 550));
        jScrollPane1.setWheelScrollingEnabled(false);

        jPanel1.setInheritsPopupMenu(true);
        jPanel1.setMaximumSize(new java.awt.Dimension(845, 32767));
        jPanel1.setMinimumSize(new java.awt.Dimension(845, 547));
        jPanel1.setPreferredSize(new java.awt.Dimension(845, 647));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setMinimumSize(new java.awt.Dimension(500, 605));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 605));
        jPanel2.setRequestFocusEnabled(false);

        dname_label.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        dname_label.setText("Donor Name:");

        dname_text.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        dname_text.setMinimumSize(new java.awt.Dimension(250, 24));
        dname_text.setPreferredSize(new java.awt.Dimension(250, 24));
        dname_text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dname_textFocusLost(evt);
            }
        });
        dname_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dname_textActionPerformed(evt);
            }
        });

        dtype_label.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        dtype_label.setText("Type ");

        dphone_label.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        dphone_label.setText("Phone ");

        d_phone_text.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        d_phone_text.setMinimumSize(new java.awt.Dimension(250, 24));
        d_phone_text.setPreferredSize(new java.awt.Dimension(250, 24));
        d_phone_text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                d_phone_textFocusLost(evt);
            }
        });

        dalt_phone_label.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        dalt_phone_label.setText("Alternate Phone");

        dalt_phone_text.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        dalt_phone_text.setMinimumSize(new java.awt.Dimension(250, 24));
        dalt_phone_text.setPreferredSize(new java.awt.Dimension(250, 24));
        dalt_phone_text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dalt_phone_textFocusLost(evt);
            }
        });
        dalt_phone_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dalt_phone_textActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_wht_bg_small.PNG"))); // NOI18N

        Title_label.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        Title_label.setText("Join New Donor");

        add_donor.setBackground(new java.awt.Color(67, 134, 250));
        add_donor.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        add_donor.setForeground(new java.awt.Color(255, 255, 255));
        add_donor.setText("Add");
        add_donor.setContentAreaFilled(false);
        add_donor.setMaximumSize(new java.awt.Dimension(51, 30));
        add_donor.setMinimumSize(new java.awt.Dimension(51, 30));
        add_donor.setOpaque(true);
        add_donor.setPreferredSize(new java.awt.Dimension(51, 30));
        add_donor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_donorActionPerformed(evt);
            }
        });

        cancel_donor.setBackground(new java.awt.Color(67, 134, 250));
        cancel_donor.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        cancel_donor.setForeground(new java.awt.Color(255, 255, 255));
        cancel_donor.setText("Cancel");
        cancel_donor.setToolTipText("");
        cancel_donor.setBorder(null);
        cancel_donor.setBorderPainted(false);
        cancel_donor.setContentAreaFilled(false);
        cancel_donor.setMaximumSize(new java.awt.Dimension(51, 25));
        cancel_donor.setMinimumSize(new java.awt.Dimension(51, 25));
        cancel_donor.setOpaque(true);
        cancel_donor.setPreferredSize(new java.awt.Dimension(51, 30));
        cancel_donor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_donorActionPerformed(evt);
            }
        });

        dtype_combobox.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        dtype_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Individual", "Restaurant", "FoodBank" }));
        dtype_combobox.setMinimumSize(new java.awt.Dimension(250, 24));
        dtype_combobox.setPreferredSize(new java.awt.Dimension(250, 24));
        dtype_combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtype_comboboxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("Email");

        demail_text.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        demail_text.setMinimumSize(new java.awt.Dimension(250, 24));
        demail_text.setPreferredSize(new java.awt.Dimension(250, 24));
        demail_text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                demail_textFocusLost(evt);
            }
        });

        city_cb.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        city_cb.setPreferredSize(new java.awt.Dimension(31, 25));
        city_cb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                city_cbItemStateChanged(evt);
            }
        });

        state_cb.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        state_cb.setMinimumSize(new java.awt.Dimension(31, 25));
        state_cb.setPreferredSize(new java.awt.Dimension(31, 25));
        state_cb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                state_cbItemStateChanged(evt);
            }
        });
        state_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                state_cbActionPerformed(evt);
            }
        });

        country_cb.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        country_cb.setMaximumSize(new java.awt.Dimension(80, 20));
        country_cb.setMinimumSize(new java.awt.Dimension(80, 20));
        country_cb.setName(""); // NOI18N
        country_cb.setPreferredSize(new java.awt.Dimension(80, 25));
        country_cb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                country_cbItemStateChanged(evt);
            }
        });
        country_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                country_cbActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setText("Where you would like to Work ?");

        emaill_label1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        emaill_label1.setText("Country");

        emaill_label2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        emaill_label2.setText("State");

        emaill_label3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        emaill_label3.setText("City");

        area_cb.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        area_cb.setPreferredSize(new java.awt.Dimension(31, 25));

        emaill_label4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        emaill_label4.setText("Area");

        uname_text.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        uname_text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                uname_textFocusLost(evt);
            }
        });

        alt_phone_label1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        alt_phone_label1.setText("User Name");

        alt_phone_label2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        alt_phone_label2.setText("Password");

        alt_phone_label3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        alt_phone_label3.setText("Retype Password");

        pass_text.setBackground(new java.awt.Color(240, 240, 240));
        pass_text.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        pass_text.setEnabled(false);
        pass_text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pass_textFocusLost(evt);
            }
        });
        pass_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_textActionPerformed(evt);
            }
        });

        pass_retype_text.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        pass_retype_text.setEnabled(false);
        pass_retype_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_retype_textActionPerformed(evt);
            }
        });
        pass_retype_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pass_retype_textKeyTyped(evt);
            }
        });

        error_msg_bottom_lb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        error_msg_bottom_lb.setForeground(new java.awt.Color(204, 0, 0));
        error_msg_bottom_lb.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setText("AddressLine");

        address_text.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        address_text.setMinimumSize(new java.awt.Dimension(6, 24));
        address_text.setName("[6, 24]"); // NOI18N
        address_text.setPreferredSize(new java.awt.Dimension(6, 24));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(Title_label)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(dphone_label)
                                        .addComponent(dalt_phone_label))
                                    .addGap(21, 21, 21)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(d_phone_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(dalt_phone_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(dtype_label)
                                        .addComponent(jLabel1)
                                        .addComponent(dname_label))
                                    .addGap(39, 39, 39)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(dname_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(demail_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(dtype_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(alt_phone_label1)
                                        .addComponent(alt_phone_label2)
                                        .addComponent(alt_phone_label3)
                                        .addComponent(emaill_label1)
                                        .addComponent(emaill_label2)
                                        .addComponent(emaill_label3)
                                        .addComponent(emaill_label4)
                                        .addComponent(jLabel4))
                                    .addGap(12, 12, 12)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(pass_text, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(uname_text)
                                        .addComponent(city_cb, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(state_cb, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(country_cb, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(area_cb, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pass_retype_text, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(address_text, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(error_msg_bottom_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(add_donor, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cancel_donor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Title_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dname_label)
                            .addComponent(dname_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(demail_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dtype_label)
                            .addComponent(dtype_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dphone_label)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(d_phone_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dalt_phone_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dalt_phone_label))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(country_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emaill_label1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(state_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emaill_label2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(city_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emaill_label3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(area_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emaill_label4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(5, 5, 5))
                    .addComponent(address_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uname_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alt_phone_label1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alt_phone_label2)
                    .addComponent(pass_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass_retype_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alt_phone_label3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(add_donor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cancel_donor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(error_msg_bottom_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(170, 20, 500, 605);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg.png"))); // NOI18N
        jLabel2.setText("kj");
        jLabel2.setMaximumSize(new java.awt.Dimension(850, 637));
        jLabel2.setMinimumSize(new java.awt.Dimension(850, 637));
        jLabel2.setPreferredSize(new java.awt.Dimension(850, 637));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 850, 550);

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void dname_textFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dname_textFocusLost
        // TODO add your handling code here:
        String regex = "[a-zA-Z]+";

        boolean isValid=check_regex(regex, dname_text.getText());

        if(isValid)
        {
            
            if(dname_text.getBackground().getGreen()!=253)
            {
                validate_all--;
            }
             dname_text.setBackground(new Color(170, 253, 197));
        }
        else{
           
           
            if(dname_text.getBackground().getGreen()==253)
            {
                validate_all++;
            }
             dname_text.setBackground(new Color(255, 186, 187));
        }
    }//GEN-LAST:event_dname_textFocusLost

    private void dname_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dname_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dname_textActionPerformed

    private void d_phone_textFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_d_phone_textFocusLost
        // TODO add your handling code here:

        String regex = "\\d{10}";

        boolean isValid=check_regex(regex, d_phone_text.getText());

        if(isValid)
        {
            
            if(d_phone_text.getBackground().getGreen()!=253)
            {
                validate_all--;
            }
            d_phone_text.setBackground(new Color(170, 253, 197));
        }
        else{
          
            if(d_phone_text.getBackground().getGreen()==253)
            {
                validate_all++;
            }
              d_phone_text.setBackground(new Color(255, 186, 187));
        }
    }//GEN-LAST:event_d_phone_textFocusLost

    private void dalt_phone_textFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dalt_phone_textFocusLost
        // TODO add your handling code here:
        String regex = "\\d{10}";

        boolean isValid=check_regex(regex, dalt_phone_text.getText());
        if(dalt_phone_text.getText().length()==0)
        {
            isValid=true;
        }
        if(isValid)
        {
           
            if(dalt_phone_text.getBackground().getGreen()!=253)
            {
                validate_all--;
            }
             dalt_phone_text.setBackground(new Color(170, 253, 197));
        }
        else{
           
            if(dalt_phone_text.getBackground().getGreen()==253)
            {
                validate_all++;
            }
             dalt_phone_text.setBackground(new Color(255, 186, 187));
        }
        
    }//GEN-LAST:event_dalt_phone_textFocusLost

    private void add_donorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_donorActionPerformed
        
         
        try
        {
            if(validate_all==0)
            {    
            String alt_phone="NULL";
            if(dalt_phone_text.getText().length()!=0)
            alt_phone="'"+dalt_phone_text.getText()+"'";
            //Data to be inserted
            int Points=0;
            
            //Connect Database Block
            Class.forName("com.mysql.jdbc.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost/foodrive","root","nimda");
            System.out.println("Connected");
            //Connect Database Block
            
            Statement st = c.createStatement();
            //Query for insert into member
            String query="INSERT INTO donor(donor_id,donor_name,email,address_line,city,state,country,type,phone,alternate_phone) " +
            "VALUES(NULL,'"+dname_text.getText()+"','"+demail_text.getText()+"','"+address_text.getText()+"','"+city_cb.getSelectedItem().toString()+"','"+state_cb.getSelectedItem().toString()+"','"+country_cb.getSelectedItem().toString()+"','"+dtype_combobox.getSelectedItem().toString()+"',"+
            "'"+d_phone_text.getText()+"','"+dalt_phone_text.getText()+"');";
            System.out.println("Runnung Query");
            //Execute query
            st.executeUpdate(query);
            System.out.println("Done");
            
            SimpleDateFormat format1DateFormat=new SimpleDateFormat("yyyy-MM-dd");
            Date now_d = new Date();
            String now=format1DateFormat.format(now_d);
            
            Statement st3Statement = c.createStatement();
            String s = "SELECT donor_id FROM donor WHERE donor_name='"+dname_text.getText()+"';";
            ResultSet rs = st.executeQuery(s);
            System.out.println(s);
            rs.next();
            int donor_id=rs.getInt("donor_id");
            
            Statement st1=c.createStatement();
            String q_insert_into_credential="INSERT INTO credentials(reference_id,username,u_password,role) " + 
                                                "VALUES("+donor_id+",'"+uname_text.getText()+"','"+pass_retype_text.getText()+"','guest');";
            
             System.out.println(q_insert_into_credential);
              st1.executeUpdate(q_insert_into_credential);
              
              
              int area_id=getAreaId(c);
                
              Statement s9=c.createStatement();
              String q_insert_into_join="INSERT INTO team_join_req(req_id,reference_id,area_id,status_flag,role) " + 
                                                "VALUES(NULL,"+donor_id+","+area_id+",0,'donor');";
              s9.executeUpdate(q_insert_into_join);
            
            
            
            
            
            
            
            
            Component j = null;
            
    
            JOptionPane.showMessageDialog(j, "Thank You for Registration.You can login after monitor confirms you!");
            this.dispose();
            }
            else{
                if(validate_all!=0){
                    JOptionPane.showMessageDialog(null,"Enterered data is not correct!..");
                }
                System.out.println(""+validate_all);
            }
       }

        catch (Exception e)
        {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error while Adding Volunteer..!");
        }
        
    }//GEN-LAST:event_add_donorActionPerformed

    private void cancel_donorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_donorActionPerformed
         dispose();
    }//GEN-LAST:event_cancel_donorActionPerformed

    private void dtype_comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtype_comboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtype_comboboxActionPerformed

    private void dalt_phone_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dalt_phone_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dalt_phone_textActionPerformed

    private void demail_textFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_demail_textFocusLost
       String regex = "^(.+)@(.+)[.](.+)";

        boolean isValid=check_regex(regex, demail_text.getText());

        if(isValid)
        {
           
            if(demail_text.getBackground().getGreen()!=253)
            {
                validate_all--;
            }
             demail_text.setBackground(new Color(170, 253, 197));
        }
        else{
           
            if(demail_text.getBackground().getGreen()==253)
            {
                validate_all++;
            }
             demail_text.setBackground(new Color(255, 186, 187));
        }
    }//GEN-LAST:event_demail_textFocusLost

    private void city_cbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_city_cbItemStateChanged
        // TODO add your handling code here:
        if(city_cb.getSelectedItem() != null){

            try {
                String city=city_cb.getSelectedItem().toString();
                Connection c=null;
                MyConnection mo= new MyConnection();
                c=mo.getMyConnection();
                //Connect Database Block

                Statement st = c.createStatement();
                String s = "SELECT DISTINCT area_name FROM area WHERE city='"+city+"';";
                ResultSet rs = st.executeQuery(s);
                area_cb.removeAllItems();
                while(rs.next()){
                    area_cb.addItem(rs.getString("area_name"));

                }
            } catch (SQLException ex) {
                Logger.getLogger(Joinus.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_city_cbItemStateChanged

    private void state_cbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_state_cbItemStateChanged
        // TODO add your handling code here:
        if(state_cb.getSelectedItem() != null){

            try {
                String state=state_cb.getSelectedItem().toString();
                Connection c=null;
                MyConnection mo= new MyConnection();
                c=mo.getMyConnection();
                //Connect Database Block

                Statement st = c.createStatement();
                String s = "SELECT DISTINCT city FROM area WHERE state='"+state+"';";
                ResultSet rs = st.executeQuery(s);
                city_cb.removeAllItems();
                while(rs.next()){
                    city_cb.addItem(rs.getString("city"));

                }
            } catch (SQLException ex) {
                Logger.getLogger(Joinus.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_state_cbItemStateChanged

    private void state_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_state_cbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_state_cbActionPerformed

    private void country_cbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_country_cbItemStateChanged
        // TODO add your handling code here:
        if(country_cb.getSelectedItem() != null){

            try {
                String country=country_cb.getSelectedItem().toString();
                Connection c=null;
                MyConnection mo= new MyConnection();
                c=mo.getMyConnection();
                //Connect Database Block

                Statement st = c.createStatement();
                String s = "SELECT DISTINCT state FROM area WHERE country='"+country+"';";
                ResultSet rs = st.executeQuery(s);
                state_cb.removeAllItems();
                while(rs.next()){
                    state_cb.addItem(rs.getString("state"));

                }
            } catch (SQLException ex) {
                Logger.getLogger(Joinus.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_country_cbItemStateChanged

    private void country_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_country_cbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_country_cbActionPerformed

    private void uname_textFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_uname_textFocusLost
        // TODO add your handling code here:
        boolean isValid=false;

        try {
            String username=uname_text.getText();
            Connection c=null;
            MyConnection mo= new MyConnection();
            c=mo.getMyConnection();
            //Connect Database Block

            String query = "SELECT reference_id FROM credentials WHERE username=?;";
            PreparedStatement pst = c.prepareStatement(query);
            pst.setString(1,username);
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                isValid=false;
                System.out.println("Username Not available..");
                error_msg_bottom_lb.setText("*Username is already taken");
            }
            else
            {
                isValid=true;
                error_msg_bottom_lb.setText("");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Joinus.class.getName()).log(Level.SEVERE, null, ex);
            isValid=false;
        }

        if(isValid)
        {

            if(uname_text.getBackground().getGreen()!=253)
            {
                validate_all--;
            }
            uname_text.setBackground(new Color(170, 253, 197));
            pass_text.enable();

            pass_text.setBackground(Color.white);

        }
        else{
            if(uname_text.getBackground().getGreen()==253)
            {
                validate_all++;
            }
            uname_text.setBackground(new Color(255, 186, 187));
            pass_text.disable();

            pass_text.setBackground(new Color(240,240,240));

        }
    }//GEN-LAST:event_uname_textFocusLost

    private void pass_textFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass_textFocusLost
        // TODO add your handling code here:
        String regex = ".{8,}";

        boolean isValid=check_regex(regex, pass_text.getText());
        if(isValid)
        {

            if(pass_text.getBackground().getGreen()!=253)
            {
                validate_all--;
            }
            pass_text.setBackground(new Color(170, 253, 197));
            error_msg_bottom_lb.setText("");
            pass_retype_text.enable();
            pass_retype_text.setBackground(Color.white);

        }
        else{
            if(pass_text.getBackground().getGreen()==253)
            {
                validate_all++;
            }
            pass_text.setBackground(new Color(255, 186, 187));
            error_msg_bottom_lb.setText("*Minimum Password length is 8");
            pass_retype_text.disable();
            pass_retype_text.setBackground(new Color(240,240,240));
        }
    }//GEN-LAST:event_pass_textFocusLost

    private void pass_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_textActionPerformed

    private void pass_retype_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_retype_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_retype_textActionPerformed

    private void pass_retype_textKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pass_retype_textKeyTyped
        // TODO add your handling code here:
        boolean isValid=false;
        if(pass_retype_text.getText() != null)
        {
            String pas_str=pass_text.getText();
            String pass_retyped_str=pass_retype_text.getText();
            pass_retyped_str=pass_retyped_str+evt.getKeyChar();
            System.out.println(pas_str.equals(pass_retyped_str));
            if(pas_str.equals(pass_retyped_str))
            {
                isValid=true;
            }
            else{
                isValid=false;
            }

            if(isValid)
            {
                if(pass_retype_text.getBackground().getGreen()!=253)
                {
                    validate_all--;
                }
                pass_retype_text.setBackground(new Color(170, 253, 197));
            }
            else
            {
                if(pass_retype_text.getBackground().getGreen()==253)
                {
                    validate_all++;
                }
                pass_retype_text.setBackground(new Color(255, 186, 187));

            }
        }
    }//GEN-LAST:event_pass_retype_textKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(joinus_donor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(joinus_donor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(joinus_donor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(joinus_donor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new joinus_donor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title_label;
    private javax.swing.JButton add_donor;
    private javax.swing.JTextField address_text;
    private javax.swing.JLabel alt_phone_label1;
    private javax.swing.JLabel alt_phone_label2;
    private javax.swing.JLabel alt_phone_label3;
    private javax.swing.JComboBox<String> area_cb;
    private javax.swing.JButton cancel_donor;
    private javax.swing.JComboBox<String> city_cb;
    private javax.swing.JComboBox<String> country_cb;
    private javax.swing.JTextField d_phone_text;
    private javax.swing.JLabel dalt_phone_label;
    private javax.swing.JTextField dalt_phone_text;
    private javax.swing.JTextField demail_text;
    private javax.swing.JLabel dname_label;
    private javax.swing.JTextField dname_text;
    private javax.swing.JLabel dphone_label;
    private javax.swing.JComboBox<String> dtype_combobox;
    private javax.swing.JLabel dtype_label;
    private javax.swing.JLabel emaill_label1;
    private javax.swing.JLabel emaill_label2;
    private javax.swing.JLabel emaill_label3;
    private javax.swing.JLabel emaill_label4;
    private javax.swing.JLabel error_msg_bottom_lb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField pass_retype_text;
    private javax.swing.JPasswordField pass_text;
    private javax.swing.JComboBox<String> state_cb;
    private javax.swing.JTextField uname_text;
    // End of variables declaration//GEN-END:variables
}
