/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.foodrive.Monitor;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import project.foodrive.MyConnection;
import project.foodrive.Volunteer.Notification_panel;

/**
 *
 * @author abcd
 */
public class Drive_details_frame extends javax.swing.JFrame {

    /**
     * Creates new form Volunteer_details_frame
     */
    private int monitor_id;
    private int area_id;
    private int drive_id;
    public Drive_details_frame() {
        initComponents();
    }
    
    public Drive_details_frame(int monitorid,int driveid,int areaid) {
        initComponents();
        monitor_id=monitorid;
        area_id=areaid;
        drive_id=driveid;
        load_drive_details();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        profile = new javax.swing.JLabel();
        get_start_time = new javax.swing.JLabel();
        personal_details = new javax.swing.JPanel();
        email_label = new javax.swing.JLabel();
        get_did = new javax.swing.JLabel();
        get_status = new javax.swing.JLabel();
        phonne_label = new javax.swing.JLabel();
        get_max_vol = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        get_moid = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        get_method = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        get_end_time = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        get_pickup = new javax.swing.JLabel();
        get_destribute = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        get_food_quantity = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(850, 550));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(850, 550));
        jScrollPane1.setName(""); // NOI18N
        jScrollPane1.setPreferredSize(new java.awt.Dimension(850, 550));

        jPanel1.setMaximumSize(new java.awt.Dimension(850, 550));
        jPanel1.setMinimumSize(new java.awt.Dimension(850, 550));

        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/drive_details.png"))); // NOI18N
        profile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        get_start_time.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        get_start_time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        get_start_time.setText("Start_Time");
        get_start_time.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        personal_details.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Drive Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 14))); // NOI18N
        personal_details.setMinimumSize(new java.awt.Dimension(539, 161));
        personal_details.setPreferredSize(new java.awt.Dimension(539, 161));

        email_label.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        email_label.setText("Status");

        get_did.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_did.setText("000");

        get_status.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_status.setText("default");

        phonne_label.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        phonne_label.setText("Max Volunteers");

        get_max_vol.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_max_vol.setText("000");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setText("Drive Id");

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel14.setText("Monitor Id");

        get_moid.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_moid.setText("000");

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel12.setText("Vol Select Method");

        get_method.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_method.setText("*method*");

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel15.setText("End Time");

        get_end_time.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_end_time.setText("0000");

        javax.swing.GroupLayout personal_detailsLayout = new javax.swing.GroupLayout(personal_details);
        personal_details.setLayout(personal_detailsLayout);
        personal_detailsLayout.setHorizontalGroup(
            personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personal_detailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(email_label)
                    .addComponent(jLabel14)
                    .addComponent(phonne_label)
                    .addComponent(jLabel12)
                    .addComponent(jLabel15))
                .addGap(30, 30, 30)
                .addGroup(personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(get_end_time)
                    .addComponent(get_did, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(get_status)
                    .addComponent(get_max_vol)
                    .addComponent(get_moid)
                    .addComponent(get_method))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        personal_detailsLayout.setVerticalGroup(
            personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personal_detailsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(get_did, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(get_status)
                    .addComponent(email_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(get_max_vol)
                    .addComponent(phonne_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(get_moid)
                    .addGroup(personal_detailsLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(get_method))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(get_end_time))
                .addGap(34, 34, 34))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Area Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 14))); // NOI18N
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setPreferredSize(new java.awt.Dimension(539, 161));

        get_pickup.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_pickup.setText("*donor_loactoion*");

        get_destribute.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_destribute.setText("*circle_location*");

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel8.setText("Destribution Location");

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel9.setText("Food Quantity");

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel7.setText("Pickup Loaction");

        get_food_quantity.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_food_quantity.setText("*no_of_needies*");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(get_destribute, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(get_pickup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(get_food_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 447, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(get_pickup))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(get_destribute))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(get_food_quantity))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(profile)
                        .addGap(0, 356, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(get_start_time, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(personal_details, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profile)
                .addGap(5, 5, 5)
                .addComponent(get_start_time)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(personal_details, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Drive_details_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Drive_details_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Drive_details_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Drive_details_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Drive_details_frame().setVisible(true);
            }
        });
    }

       private void load_drive_details(){
        
        try {
            System.out.println("here 0");
            Connection c=null;
            MyConnection mo= new MyConnection();
            c=mo.getMyConnection();
            System.out.println("connected");
            
            String query="SELECT drive.drive_id,drive.monitor_id, " +
                            "drive.status, " +
                            "drive.max_volunteers, " +
                            "drive.vol_select_method, " +
                            "drive.start_time, " +
                            "drive.end_time, " +
                            "donor.address_line1, " +
                            "donor.city, " +
                            "donor.state, " +
                            "donor.country, " +
                            "needy_circle.address_line, " +
                            "needy_circle.landmark, " +
                            "distribute_to.food_quantity, " +
                            "area.area_id " +
                            "FROM ((((drive " +
                            "INNER JOIN donor " +
                            "ON drive.area_id=donor.area_id) " +
                            "INNER JOIN needy_circle " +
                            "ON drive.area_id=needy_circle.area_id) " +
                            "INNER JOIN distribute_to " +
                            "ON needy_circle.circle_id=distribute_to.circle_id) " +
                            "INNER JOIN area " +
                            "ON drive.area_id=area.area_id) " +
                            "WHERE drive.drive_id=? " +
                            "AND area.area_id=?;";
            
            PreparedStatement pst=c.prepareStatement(query);
            pst.setInt(1,drive_id);
            pst.setInt(2,area_id);
        
            ResultSet rs=pst.executeQuery();
             
            while(rs.next()){ 
                System.out.println(rs.getInt("drive_id"));
                 this.get_did.setText(""+rs.getInt("drive_id"));
                 this.get_moid.setText(""+rs.getInt("monitor_id"));
                 this.get_status.setText(rs.getString("status"));
                 this.get_max_vol.setText(""+rs.getInt("max_volunteers"));
                 this.get_method.setText(rs.getString("vol_select_method"));
  
                this.get_pickup.setText(rs.getString("address_line1")+", "+rs.getString("city")+", "+rs.getString("state")+", "+rs.getString("country") );
                 this.get_destribute.setText(rs.getString("address_line")+", "+rs.getString("landmark"));
                 this.get_food_quantity.setText("Around "+""+rs.getInt("food_quantity") +" Peoples");
                 this.get_start_time.setText(rs.getString("start_time"));
            }
            
           
           c.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(Notification_panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel email_label;
    private javax.swing.JLabel get_destribute;
    private javax.swing.JLabel get_did;
    private javax.swing.JLabel get_end_time;
    private javax.swing.JLabel get_food_quantity;
    private javax.swing.JLabel get_max_vol;
    private javax.swing.JLabel get_method;
    private javax.swing.JLabel get_moid;
    private javax.swing.JLabel get_pickup;
    private javax.swing.JLabel get_start_time;
    private javax.swing.JLabel get_status;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel personal_details;
    private javax.swing.JLabel phonne_label;
    private javax.swing.JLabel profile;
    // End of variables declaration//GEN-END:variables
}
