/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.foodrive.Monitor;

import project.foodrive.Admin.*;
import Testing.*;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import project.foodrive.Admin.Add_volunteer;
import project.foodrive.MyConnection;


/**
 *
 * @author abcd
 */
public class Monitor_Chapter_view extends javax.swing.JPanel {

    /**
     * Creates new form Admin_volunteer_view
     */
    
    private int monitor_id=-1;
    private int area_id=-1;
    private int circle_id=-1;
    Monitor_dashboard mainFrame;
    public Monitor_Chapter_view() {
        initComponents();
        
       
    }
    
     private Color mouseExitedColor = new Color(102,102,255);
    private Color mouseEnteredColor = new Color(75,80,200);
    private Color mouseClickedColor = new Color(102,102,255);
    private Color passiveFontColor = new Color(255,255,255);
    private Color activeFontColor = new Color(255,255,255);
    private int selected_option_from_left=0;
    private Color searchMouseEnterColor = new Color(220,220,220);
    private Color searchMouseExitColor = new Color(240,240,240);
    
    
    Monitor_Chapter_view(int circle_id, int area_id,Monitor_dashboard obj) {
        initComponents();
        this.circle_id=circle_id;
        this.area_id=area_id;
        mainFrame=obj;
        load_circle("");
     
    }
    
     private void setAllOptionAsNonSelected(){
        volunteer_pan.setBackground(mouseExitedColor);
        volunteer_label.setForeground(passiveFontColor);
     }
     
     public void load_circle(String searchstr){
         try {
            Connection c=null;
            MyConnection mo= new MyConnection();
            c=mo.getMyConnection();
            
            //This query is also used for search
            String query="select * from needy_circle where area_id=? and " +
                            "concat_ws(',',circle_id,no_of_peoples,address_line,landmark) like '%,"+searchstr+"%';";
            PreparedStatement pst=c.prepareStatement(query);
            pst.setInt(1, area_id);
            ResultSet rs=pst.executeQuery();
            records_panel.removeAll();
            while(rs.next()){
                
                System.out.println("in chpate view "+rs.getInt("circle_id"));
                records_panel.add(new Chapter_RecordPanel(rs.getInt("circle_id"),area_id,mainFrame));
                
            }
            records_panel.repaint();
            records_panel.revalidate();
            c.close();
        } catch (SQLException ex) {
             ex.printStackTrace();
             System.out.println("load_circle "+ex.getMessage());
        }
     }
     
     
     
    private void setColorToAllSearchEle(Color c){
        jPanel3.setBackground(c);
        tfSearch.setBackground(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        volunteer_pan = new javax.swing.JPanel();
        volunteer_label = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        records_panel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        tfSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(850, 550));
        setMinimumSize(new java.awt.Dimension(850, 550));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jScrollPane1.setMaximumSize(new java.awt.Dimension(850, 550));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(850, 550));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));
        jPanel1.setMaximumSize(new java.awt.Dimension(850, 550));
        jPanel1.setMinimumSize(new java.awt.Dimension(850, 550));
        jPanel1.setPreferredSize(new java.awt.Dimension(850, 550));
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel1.setText("Circles in");

        volunteer_pan.setBackground(new java.awt.Color(102, 102, 255));
        volunteer_pan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        volunteer_pan.setMaximumSize(new java.awt.Dimension(250, 45));
        volunteer_pan.setMinimumSize(new java.awt.Dimension(250, 45));
        volunteer_pan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volunteer_panMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                volunteer_panMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                volunteer_panMouseExited(evt);
            }
        });

        volunteer_label.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        volunteer_label.setForeground(new java.awt.Color(255, 255, 255));
        volunteer_label.setText("Add Circle");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add_circle.png"))); // NOI18N

        javax.swing.GroupLayout volunteer_panLayout = new javax.swing.GroupLayout(volunteer_pan);
        volunteer_pan.setLayout(volunteer_panLayout);
        volunteer_panLayout.setHorizontalGroup(
            volunteer_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(volunteer_panLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(volunteer_label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        volunteer_panLayout.setVerticalGroup(
            volunteer_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, volunteer_panLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(volunteer_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(volunteer_label))
                .addGap(5, 5, 5))
        );

        jScrollPane2.setMaximumSize(new java.awt.Dimension(790, 32767));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(790, 300));

        records_panel.setBackground(new java.awt.Color(255, 255, 255));
        records_panel.setMaximumSize(new java.awt.Dimension(800, 32767));
        records_panel.setLayout(new javax.swing.BoxLayout(records_panel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane2.setViewportView(records_panel);

        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
        });

        tfSearch.setBackground(new java.awt.Color(240, 240, 240));
        tfSearch.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        tfSearch.setForeground(new java.awt.Color(153, 153, 153));
        tfSearch.setText("Search");
        tfSearch.setBorder(null);
        tfSearch.setSelectionColor(new java.awt.Color(102, 102, 102));
        tfSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfSearchMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfSearchMousePressed(evt);
            }
        });
        tfSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSearchActionPerformed(evt);
            }
        });
        tfSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfSearchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfSearchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfSearchKeyTyped(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(255, 255, 255));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search1.png"))); // NOI18N
        btnSearch.setContentAreaFilled(false);
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.setFocusable(false);
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchMouseExited(evt);
            }
        });
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 51, 255));
        jLabel3.setMaximumSize(new java.awt.Dimension(0, 2));
        jLabel3.setOpaque(true);
        jLabel3.setPreferredSize(new java.awt.Dimension(0, 2));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setText("ID");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setText("AddressLine");

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setText("Landmark");

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel7.setText("No_of_peoples");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel4)
                                .addGap(35, 35, 35)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 287, Short.MAX_VALUE)
                                .addComponent(volunteer_pan, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(volunteer_pan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tfSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSearchKeyReleased
        // TODO add your handling code here:
        if(tfSearch.getText().isEmpty()==true)
        {
            tfSearch.setText("Search");
            tfSearch.setCaretPosition(0);
            tfSearch.setForeground(new java.awt.Color(153,153,153));
        }
    }//GEN-LAST:event_tfSearchKeyReleased

    private void tfSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSearchKeyPressed
        // TODO add your handling code here:
        if(tfSearch.getForeground()!=Color.BLACK)
        {
            if(tfSearch.getText().equals("Search"))
            { tfSearch.setText("");
            }

        }
        tfSearch.setForeground(Color.BLACK);

    }//GEN-LAST:event_tfSearchKeyPressed

    private void tfSearchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfSearchMousePressed
        // TODO add your handling code here:
        tfSearch.setCaretPosition(0);
    }//GEN-LAST:event_tfSearchMousePressed

    private void volunteer_panMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volunteer_panMouseExited
        // TODO add your handling code here:
        if(selected_option_from_left!=1)
        {
            volunteer_pan.setBackground(mouseExitedColor);
            volunteer_label.setForeground(passiveFontColor);
        }

    }//GEN-LAST:event_volunteer_panMouseExited

    private void volunteer_panMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volunteer_panMouseEntered
        // TODO add your handling code here:
       
            volunteer_pan.setBackground(mouseEnteredColor);
            volunteer_label.setForeground(activeFontColor);
       
    }//GEN-LAST:event_volunteer_panMouseEntered

    private void volunteer_panMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volunteer_panMouseClicked
        setAllOptionAsNonSelected();
        //volunteer_pan.setBackground(mouseClickedColor);
        volunteer_label.setBackground(mouseEnteredColor);
        volunteer_label.setForeground(activeFontColor);
        //records_panel.add(new RecordPanel());
        //records_panel.revalidate();
        //records_panel.repaint();
        //System.out.println("W : "+records_panel.getWidth()+" H : "+records_panel.getHeight());
        //selected_option_from_left=1;
        //this.hide();
       
        new Add_needy_circle().show();
    }//GEN-LAST:event_volunteer_panMouseClicked

    private void tfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSearchActionPerformed

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        // TODO add your handling code here:
        setColorToAllSearchEle(searchMouseEnterColor);
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        // TODO add your handling code here:
        setColorToAllSearchEle(searchMouseExitColor);
    }//GEN-LAST:event_jPanel3MouseExited

    private void tfSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfSearchMouseEntered
        // TODO add your handling code here:
        setColorToAllSearchEle(searchMouseEnterColor);
    }//GEN-LAST:event_tfSearchMouseEntered

    private void tfSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfSearchMouseExited
        // TODO add your handling code here:
        setColorToAllSearchEle(searchMouseExitColor);
    }//GEN-LAST:event_tfSearchMouseExited

    private void btnSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseEntered
        // TODO add your handling code here:
        setColorToAllSearchEle(searchMouseEnterColor);
    }//GEN-LAST:event_btnSearchMouseEntered

    private void btnSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseExited
        // TODO add your handling code here:
        setColorToAllSearchEle(searchMouseExitColor);
    }//GEN-LAST:event_btnSearchMouseExited

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formComponentShown

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown
        // TODO add your handling code here:
        records_panel.add(new Chapter_RecordPanel());
        records_panel.add(new Chapter_RecordPanel());
        records_panel.add(new Chapter_RecordPanel());
        records_panel.revalidate();
        records_panel.repaint();
    }//GEN-LAST:event_jPanel1ComponentShown

    private void tfSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSearchKeyTyped
        String search_text=tfSearch.getText();
        if(evt.getKeyCode()!=java.awt.event.KeyEvent.VK_BACK_SPACE)
        {
            System.out.println("Im in BACKSPACE");
            search_text=search_text+evt.getKeyChar();
        }
        System.out.println(search_text+" "+search_text.length());
        load_circle(search_text);
    }//GEN-LAST:event_tfSearchKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel records_panel;
    private javax.swing.JTextField tfSearch;
    private javax.swing.JLabel volunteer_label;
    private javax.swing.JPanel volunteer_pan;
    // End of variables declaration//GEN-END:variables
}
