/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.foodrive.Monitor;

import project.foodrive.Admin.*;
import Testing.*;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import project.foodrive.Admin.Add_volunteer;
import project.foodrive.MyConnection;

/**
 *
 * @author abcd
 */
public class Team_join_req_view_t extends javax.swing.JPanel {

    /**
     * Creates new form Admin_volunteer_view
     */
    int monitor_id=-1;
    int area_id=-1;
    private int volunteer_join_count=0;
    private int donor_join_count=0;
    private Monitor_dashboard monitor_dashboard;
    public Team_join_req_view_t() {
        initComponents();
        
    }
    
    public Team_join_req_view_t(int monitorid,int areaid,Monitor_dashboard obj) {
        initComponents();
        monitor_id=monitorid;
        area_id=areaid;
        monitor_dashboard=obj;
        load_req();
    }
    
    private void refresh_count(){
        vol_join_req.setText(""+volunteer_join_count);
        donor_join_req.setText(""+donor_join_count);
    }
    
    private void load_req()
    {
        try {
            Connection c=null;
            MyConnection mo= new MyConnection();
            c=mo.getMyConnection();
            //get volunteer req count
            String query="SELECT COUNT(req_id) AS count FROM team_join_req WHERE area_id=? "
                    + " AND status_flag=0 AND role='volunteer';";
            
            PreparedStatement pst=c.prepareStatement(query);
            pst.setInt(1, area_id);
            ResultSet rs=pst.executeQuery();
            
            if(rs.next()){
                volunteer_join_count=rs.getInt("count");
            }
            
            //get donor
            query="SELECT COUNT(req_id) AS count FROM team_join_req WHERE area_id=? "
                    + " AND status_flag=0 AND role='donor';";
            
            pst=c.prepareStatement(query);
            pst.setInt(1, area_id);
            rs=pst.executeQuery();
            
            if(rs.next()){
                donor_join_count=rs.getInt("count");
            }
            
            refresh_count();
            //join_count.setText(""+count);
        } catch (SQLException ex) {
            Logger.getLogger(Monitor_Notification_panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private Color mouseExitedColor = new Color(240,240,240);
    private Color mouseEnteredColor = new Color(190,190,190);
    private Color mouseClickedColor = new Color(215,219,227);
    private Color passiveFontColor = new Color(51,51,51);
    private Color activeFontColor = new Color(51,51,51);
    private int selected_option_from_left=0;
    private Color searchMouseEnterColor = new Color(220,220,220);
    private Color searchMouseExitColor = new Color(240,240,240);
    
     private void setAllOptionAsNonSelected(){
        
     }
     
    private void setColorToAllSearchEle(Color c){
        //jPanel3.setBackground(c);
        //tfSearch.setBackground(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        vol_req_btn = new javax.swing.JButton();
        donor_req_btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        vol_join_req = new javax.swing.JLabel();
        donor_join_req = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(850, 550));
        setMinimumSize(new java.awt.Dimension(850, 550));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jScrollPane1.setMaximumSize(new java.awt.Dimension(850, 550));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(850, 550));

        jPanel1.setMaximumSize(new java.awt.Dimension(850, 550));
        jPanel1.setMinimumSize(new java.awt.Dimension(850, 550));
        jPanel1.setPreferredSize(new java.awt.Dimension(850, 550));
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 30)); // NOI18N
        jLabel1.setText("Team Join Request");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel2.setText("Volunteer Join Request");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel3.setText("Donor Join Request");

        vol_req_btn.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        vol_req_btn.setText("View..");
        vol_req_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vol_req_btnActionPerformed(evt);
            }
        });

        donor_req_btn.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        donor_req_btn.setText("View..");
        donor_req_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donor_req_btnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setText("Request(s)");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setText("Request(s)");

        vol_join_req.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        vol_join_req.setText("0");

        donor_join_req.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        donor_join_req.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(112, 112, 112)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(donor_join_req)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(vol_join_req)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(vol_req_btn)
                    .addComponent(donor_req_btn))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(vol_req_btn)
                    .addComponent(jLabel4)
                    .addComponent(vol_join_req))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(donor_join_req)
                    .addComponent(donor_req_btn))
                .addContainerGap(375, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formComponentShown

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown
        // TODO add your handling code here:
        //records_panel.add(new RecordPanel());
        //records_panel.add(new RecordPanel());
        //records_panel.add(new RecordPanel());
        //records_panel.revalidate();
        //records_panel.repaint();
    }//GEN-LAST:event_jPanel1ComponentShown

    private void donor_req_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donor_req_btnActionPerformed
        // TODO add your handling code here:
        monitor_dashboard.load_in_main_panel(new Donor_join_req_view(monitor_id,area_id));
    }//GEN-LAST:event_donor_req_btnActionPerformed

    private void vol_req_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vol_req_btnActionPerformed
        // TODO add your handling code here:
        monitor_dashboard.load_in_main_panel(new Volunteer_join_req_view(monitor_id,area_id));
    }//GEN-LAST:event_vol_req_btnActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel donor_join_req;
    private javax.swing.JButton donor_req_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel vol_join_req;
    private javax.swing.JButton vol_req_btn;
    // End of variables declaration//GEN-END:variables
}
