/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.foodrive.Monitor;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import project.foodrive.MyConnection;
import project.foodrive.Volunteer.Notification_panel;

/**
 *
 * @author abcd
 */
public class Volunteer_details_frame extends javax.swing.JFrame {

    /**
     * Creates new form Volunteer_details_frame
     */
    private int member_id;
    private int area_id;
    
    public Volunteer_details_frame() {
        initComponents();
    }
    
    public Volunteer_details_frame(int memberid,int areaid) {
        initComponents();
        member_id=memberid;
        area_id=areaid;
        load_volunteer_details();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        profile = new javax.swing.JLabel();
        get_name = new javax.swing.JLabel();
        personal_details = new javax.swing.JPanel();
        email_label = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        get_mid = new javax.swing.JLabel();
        get_type = new javax.swing.JLabel();
        get_email = new javax.swing.JLabel();
        phonne_label = new javax.swing.JLabel();
        get_phone = new javax.swing.JLabel();
        alt_phone_label = new javax.swing.JLabel();
        get_alt_phone = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        get_dob = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        get_joindate = new javax.swing.JLabel();
        get_gender = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        get_age = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        get_experience = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        get_points = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        get_country = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        get_state = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        get_city = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        get_area = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        get_area_name = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(850, 550));
        setMinimumSize(new java.awt.Dimension(850, 550));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(850, 550));
        jScrollPane1.setName(""); // NOI18N
        jScrollPane1.setPreferredSize(new java.awt.Dimension(850, 550));

        jPanel1.setMaximumSize(new java.awt.Dimension(850, 550));
        jPanel1.setMinimumSize(new java.awt.Dimension(850, 550));

        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        profile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        get_name.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        get_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        get_name.setText("Name");
        get_name.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        personal_details.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Personal Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 14))); // NOI18N
        personal_details.setPreferredSize(new java.awt.Dimension(541, 190));

        email_label.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        email_label.setText("Email ");

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel13.setText("Type");

        get_mid.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_mid.setText("1");

        get_type.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_type.setText("Individual");

        get_email.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_email.setText("abhishekKondekar@gmail.com");

        phonne_label.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        phonne_label.setText("Phone");

        get_phone.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_phone.setText("9552978568");

        alt_phone_label.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        alt_phone_label.setText("Alternate Phone ");

        get_alt_phone.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_alt_phone.setText("8668380941");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setText("Member Id");

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel14.setText("Date of Birth");

        get_dob.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_dob.setText("Date of Birth");

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("Join date ");

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel7.setText("Gender");

        get_joindate.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_joindate.setText("10-12-2018");

        get_gender.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_gender.setText("Male");

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel8.setText("Age");

        get_age.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_age.setText("20");

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel10.setText("Experience");

        get_experience.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_experience.setText("5 months");

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel9.setText("Points");

        get_points.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_points.setText("10");

        javax.swing.GroupLayout personal_detailsLayout = new javax.swing.GroupLayout(personal_details);
        personal_details.setLayout(personal_detailsLayout);
        personal_detailsLayout.setHorizontalGroup(
            personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personal_detailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(personal_detailsLayout.createSequentialGroup()
                        .addGroup(personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personal_detailsLayout.createSequentialGroup()
                                .addGroup(personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(alt_phone_label)
                                    .addComponent(jLabel4)
                                    .addComponent(email_label)
                                    .addComponent(phonne_label))
                                .addGroup(personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(personal_detailsLayout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addGroup(personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(get_mid, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(get_email)
                                            .addComponent(get_phone)))
                                    .addGroup(personal_detailsLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(get_type)
                                            .addComponent(get_alt_phone)
                                            .addComponent(get_dob)))))
                            .addComponent(jLabel13))
                        .addGap(86, 86, 86)
                        .addGroup(personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(60, 60, 60)
                        .addGroup(personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(get_points)
                            .addComponent(get_experience)
                            .addComponent(get_age)
                            .addComponent(get_gender)
                            .addComponent(get_joindate))))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        personal_detailsLayout.setVerticalGroup(
            personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personal_detailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personal_detailsLayout.createSequentialGroup()
                        .addGroup(personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(get_mid)
                            .addComponent(jLabel1)
                            .addComponent(get_joindate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(get_email)
                            .addComponent(jLabel7)
                            .addComponent(get_gender))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(get_phone)
                            .addComponent(jLabel8)
                            .addComponent(get_age))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(get_alt_phone)
                            .addComponent(jLabel10)
                            .addComponent(get_experience)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personal_detailsLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(email_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phonne_label)
                        .addGap(11, 11, 11)
                        .addComponent(alt_phone_label)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(get_type)
                    .addComponent(jLabel9)
                    .addComponent(get_points))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(get_dob))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Address Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 14)))); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(539, 161));

        get_country.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_country.setText("country");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("Country");

        get_state.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_state.setText("state");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("State");

        get_city.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_city.setText("city");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setText("City");

        get_area.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_area.setText("area_id");

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setText("Area Name");

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel11.setText("Area_id");

        get_area_name.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_area_name.setText("area_name");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(get_area, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(get_country, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(get_state, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(get_city, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(get_area_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(278, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(get_area))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(get_area_name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(get_country))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(get_state))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(get_city))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(get_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 10, Short.MAX_VALUE)
                                .addComponent(personal_details, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 18, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(370, 370, 370)
                                .addComponent(profile)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profile)
                .addGap(5, 5, 5)
                .addComponent(get_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(personal_details, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Volunteer_details_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Volunteer_details_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Volunteer_details_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Volunteer_details_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Volunteer_details_frame().setVisible(true);
            }
        });
    }

       private void load_volunteer_details(){
        
        try {
            System.out.println("here 0");
            Connection c=null;
            MyConnection mo= new MyConnection();
            c=mo.getMyConnection();
            System.out.println("connected");
            String query="SELECT member.member_id,member.fname,member.lname,member.email,member.phone,member.alternate_phone,member.dob,member.gender,member.points,member.joindate,volunteer.type,area.area_id,area.area_name,area.city,area.state,area.country FROM ((member INNER JOIN volunteer ON member.member_id=volunteer.member_id) INNER JOIN area ON area.area_id=volunteer.area_id) WHERE member.member_id=?;";

            
            PreparedStatement pst=c.prepareStatement(query);
            pst.setInt(1,member_id);
            ResultSet rs=pst.executeQuery();
             
            while(rs.next()){
               this.get_mid.setText(""+rs.getInt("member_id"));
               this.get_email.setText(rs.getString("email"));
               this.get_phone.setText(rs.getString("phone"));
               this.get_alt_phone.setText(rs.getString("alternate_phone"));
               this.get_type.setText(rs.getString("type")); 
              this.get_dob.setText(""+rs.getString("dob"));
               this.get_city.setText(rs.getString("city"));
               this.get_joindate.setText(rs.getString("joindate"));
               this.get_gender.setText(rs.getString("gender"));
               this.get_points.setText(""+rs.getInt("points"));
               this.get_state.setText(rs.getString("state"));
               this.get_country.setText(rs.getString("country"));
               this.get_area.setText(""+rs.getInt("area_id"));
               this.get_name.setText(rs.getString("fname")+" "+rs.getString("lname"));
               this.get_area_name.setText(rs.getString("area_name"));
            }
            
            //get Experience
            query="CALL getExperienceOfMember(?)";
            pst=c.prepareStatement(query);
            pst.setInt(1,member_id);
            rs=pst.executeQuery();
            if(rs.next()){
                this.get_experience.setText((rs.getString("experience")));
            }
            
            query="CALL getAgeOfMember(?)";
            pst=c.prepareStatement(query);
            pst.setInt(1,member_id);
            rs=pst.executeQuery();
            if(rs.next()){
                this.get_age.setText((rs.getString("age")));
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Notification_panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alt_phone_label;
    private javax.swing.JLabel email_label;
    private javax.swing.JLabel get_age;
    private javax.swing.JLabel get_alt_phone;
    private javax.swing.JLabel get_area;
    private javax.swing.JLabel get_area_name;
    private javax.swing.JLabel get_city;
    private javax.swing.JLabel get_country;
    private javax.swing.JLabel get_dob;
    private javax.swing.JLabel get_email;
    private javax.swing.JLabel get_experience;
    private javax.swing.JLabel get_gender;
    private javax.swing.JLabel get_joindate;
    private javax.swing.JLabel get_mid;
    private javax.swing.JLabel get_name;
    private javax.swing.JLabel get_phone;
    private javax.swing.JLabel get_points;
    private javax.swing.JLabel get_state;
    private javax.swing.JLabel get_type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel personal_details;
    private javax.swing.JLabel phonne_label;
    private javax.swing.JLabel profile;
    // End of variables declaration//GEN-END:variables
}
