/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.foodrive.Monitor;

import project.foodrive.Admin.*;
import Testing.*;
//import com.mysql.jdbc.CallableStatement;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.border.Border;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import javax.swing.border.EtchedBorder;
import project.foodrive.MyConnection;
import project.foodrive.Volunteer.Notification_panel;

/**
 *
 * @author abcd
 */
public class Volunteer_join_RecordPanel extends javax.swing.JPanel {

    /**
     * Creates new form recordPanel
     */
    private int req_id;
    private Volunteer_join_req_view parent;
    public Volunteer_join_RecordPanel() {
        initComponents();
    }
    
    public Volunteer_join_RecordPanel(int reqid,Volunteer_join_req_view parent) {
        initComponents();
        req_id=reqid;
        this.parent=parent;
        load_req();
    }
    
    
    
    private void load_req() {
        try {
            Connection c=null;
            MyConnection mo= new MyConnection();
            c=mo.getMyConnection();
            
            //String query="{(CALL getMemberByReqID(?)};";
            String query="CALL getMemberByReqID(?)";
            //CallableStatement call=(CallableStatement) c.prepareCall(query);
            PreparedStatement call=c.prepareStatement(query);
            call.setInt(1, req_id);
            ResultSet rs=call.executeQuery();
            
            while(rs.next()){
                //System.out.println("In Record panel rs.next loop");
                this.Id.setText(""+rs.getInt("member_id"));
                this.fname_text.setText(rs.getString("fname"));
                this.lname_text.setText(rs.getString("lname"));
                this.occupation_text.setText(rs.getString("occupation"));
                this.age_text.setText(""+rs.getInt("age"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Monitor_Notification_panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    private Color recordPanMouseEnterColor = new Color(220,220,220);
    private Color recordPanMouseExitColor = new Color(255,255,255);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Id = new javax.swing.JLabel();
        fname_text = new javax.swing.JLabel();
        lname_text = new javax.swing.JLabel();
        accept_btn = new javax.swing.JButton();
        reject_btn = new javax.swing.JButton();
        age_text = new javax.swing.JLabel();
        occupation_text = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(790, 40));
        setMinimumSize(new java.awt.Dimension(790, 40));
        setPreferredSize(new java.awt.Dimension(790, 40));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        Id.setBackground(new java.awt.Color(255, 255, 255));
        Id.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Id.setText("<id>");

        fname_text.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        fname_text.setText("FirstName");

        lname_text.setBackground(new java.awt.Color(204, 204, 204));
        lname_text.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lname_text.setText("LastName");

        accept_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        accept_btn.setText("Accept");
        accept_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accept_btnActionPerformed(evt);
            }
        });

        reject_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        reject_btn.setText("reject");
        reject_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reject_btnActionPerformed(evt);
            }
        });

        age_text.setBackground(new java.awt.Color(204, 204, 204));
        age_text.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        age_text.setText("Age");

        occupation_text.setBackground(new java.awt.Color(204, 204, 204));
        occupation_text.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        occupation_text.setText("Occupation");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Id, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fname_text, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(lname_text, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(age_text, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(occupation_text, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(accept_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reject_btn)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Id, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fname_text)
                    .addComponent(lname_text)
                    .addComponent(accept_btn)
                    .addComponent(reject_btn)
                    .addComponent(age_text)
                    .addComponent(occupation_text))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
        this.setBackground(recordPanMouseEnterColor);
        Border raisedBevelBorder = BorderFactory.createRaisedBevelBorder();
        this.setBorder(raisedBevelBorder);
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        // TODO add your handling code here:
        this.setBackground(recordPanMouseExitColor);
        Border raisedEtchedBorder = new EtchedBorder(EtchedBorder.RAISED);
        this.setBorder(raisedEtchedBorder);
    }//GEN-LAST:event_formMouseExited

    private void accept_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accept_btnActionPerformed
        try {
            Connection c=null;
            MyConnection mo= new MyConnection();
            c=mo.getMyConnection();
            
            String query="UPDATE team_join_req SET status_flag=1 WHERE req_id=?;";
            // System.out.println(notification_id);
            PreparedStatement pst=c.prepareStatement(query);
            pst.setInt(1, req_id);
            int ack=pst.executeUpdate();
            this.setVisible(false);
            this.parent.decrementReqCount();
            
        } catch (SQLException ex) {
            Logger.getLogger(Notification_panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_accept_btnActionPerformed

    private void reject_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reject_btnActionPerformed
        // TODO add your handling code here:
        try {
            Connection c=null;
            MyConnection mo= new MyConnection();
            c=mo.getMyConnection();
            
            String query="UPDATE team_join_req SET status_flag=2 WHERE req_id=?;";
            // System.out.println(notification_id);
            PreparedStatement pst=c.prepareStatement(query);
            pst.setInt(1, req_id);
            int ack=pst.executeUpdate();
            this.setVisible(false);
            this.parent.decrementReqCount();
        } catch (SQLException ex) {
            Logger.getLogger(Notification_panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_reject_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Id;
    private javax.swing.JButton accept_btn;
    private javax.swing.JLabel age_text;
    private javax.swing.JLabel fname_text;
    private javax.swing.JLabel lname_text;
    private javax.swing.JLabel occupation_text;
    private javax.swing.JButton reject_btn;
    // End of variables declaration//GEN-END:variables

    
}
