/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.foodrive.Admin;

import Testing.*;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.border.Border;
import javax.swing.BorderFactory;
import javax.swing.border.EtchedBorder;
import project.foodrive.MyConnection;
import project.foodrive.Volunteer.Notification_panel;

/**
 *
 * @author abcd
 */
public class Chapter_RecordPanel extends javax.swing.JPanel {

    /**
     * Creates new form recordPanel
     */
    int area_id=-1;
    public Chapter_RecordPanel() {
        initComponents();
    }
public Chapter_RecordPanel(int areaid){
    initComponents();
    area_id=areaid;
    load_chapter();
}

private void load_chapter(){
    try{
        Connection c=null;
            MyConnection mo= new MyConnection();
            c=mo.getMyConnection();
            String query="SELECT area_id,country,state,city,monitor_id FROM area WHERE area_id=?";
            
            PreparedStatement pst=c.prepareStatement(query);
            pst.setInt(1,area_id);
            ResultSet rs=pst.executeQuery();
            
            while(rs.next()){
                //System.out.println("In Record panel rs.next loop");
                this.area_id_text.setText(""+rs.getInt("area_id"));
                this.country_text.setText(rs.getString("country"));
                this.state_text.setText(rs.getString("state"));
                this.city_text.setText(rs.getString("city"));
                System.out.println(""+rs.getInt("monitor_id"));
                if(rs.getInt("monitor_id")==0){
                    assign_btn.setEnabled(true);
                    
                }
                else{
                    assign_btn.setEnabled(false);
                }
            }
           
           
            
    }
    catch (SQLException ex) {
            Logger.getLogger(Notification_panel.class.getName()).log(Level.SEVERE, null, ex);
        }
}

    private Color recordPanMouseEnterColor = new Color(220,220,220);
    private Color recordPanMouseExitColor = new Color(255,255,255);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        state_text = new javax.swing.JLabel();
        viewDetailsIcon = new javax.swing.JLabel();
        assign_btn = new javax.swing.JButton();
        area_id_text = new javax.swing.JLabel();
        country_text = new javax.swing.JLabel();
        city_text = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(790, 4));
        setMinimumSize(new java.awt.Dimension(790, 40));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(790, 40));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        state_text.setBackground(new java.awt.Color(204, 204, 204));
        state_text.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        state_text.setText("State");

        viewDetailsIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewDetailsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/details-small.png"))); // NOI18N
        viewDetailsIcon.setAlignmentY(1.0F);
        viewDetailsIcon.setMaximumSize(new java.awt.Dimension(40, 40));
        viewDetailsIcon.setMinimumSize(new java.awt.Dimension(40, 40));
        viewDetailsIcon.setPreferredSize(new java.awt.Dimension(40, 40));
        viewDetailsIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewDetailsIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewDetailsIconMouseExited(evt);
            }
        });

        assign_btn.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        assign_btn.setText("Assign Monitor");
        assign_btn.setEnabled(false);
        assign_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assign_btnActionPerformed(evt);
            }
        });

        area_id_text.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        area_id_text.setText("Area_id");

        country_text.setBackground(new java.awt.Color(204, 204, 204));
        country_text.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        country_text.setText("Country");

        city_text.setBackground(new java.awt.Color(204, 204, 204));
        city_text.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        city_text.setText("City");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(area_id_text)
                .addGap(51, 51, 51)
                .addComponent(country_text, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(state_text, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(city_text, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(viewDetailsIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(assign_btn)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(assign_btn)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(country_text)
                        .addComponent(area_id_text)
                        .addComponent(state_text)
                        .addComponent(city_text))
                    .addComponent(viewDetailsIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
        this.setBackground(recordPanMouseEnterColor);
        Border raisedBevelBorder = BorderFactory.createRaisedBevelBorder();
        this.setBorder(raisedBevelBorder);
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        // TODO add your handling code here:
        this.setBackground(recordPanMouseExitColor);
        Border raisedEtchedBorder = new EtchedBorder(EtchedBorder.RAISED);
        this.setBorder(raisedEtchedBorder);
    }//GEN-LAST:event_formMouseExited

    private void viewDetailsIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewDetailsIconMouseEntered
        // TODO add your handling code here:
        Border raisedBevelBorder = BorderFactory.createRaisedBevelBorder();
        this.viewDetailsIcon.setBorder(raisedBevelBorder); 
        formMouseEntered(evt);
    }//GEN-LAST:event_viewDetailsIconMouseEntered

    private void viewDetailsIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewDetailsIconMouseExited
        // TODO add your handling code here:
        this.viewDetailsIcon.setBorder(BorderFactory.createEmptyBorder());
        formMouseExited(evt);
    }//GEN-LAST:event_viewDetailsIconMouseExited

    private void assign_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assign_btnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_assign_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel area_id_text;
    private javax.swing.JButton assign_btn;
    private javax.swing.JLabel city_text;
    private javax.swing.JLabel country_text;
    private javax.swing.JLabel state_text;
    private javax.swing.JLabel viewDetailsIcon;
    // End of variables declaration//GEN-END:variables
}
