/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Testing;

import java.awt.Component;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import project.foodrive.MyConnection;


/**
 *
 * @author INTEL COREi3
 */
public class Add_Area extends javax.swing.JFrame {

    /**
     * Creates new form Add_Area
     */
    public Add_Area() {
        initComponents();
        load_cities();
    }
    public void load_cities(){
        try {
            Connection c=null;
            //Connect Database Block
            MyConnection mo= new MyConnection();
            c=mo.getMyConnection();
            Statement st = c.createStatement();
            String s = "select * from countries";
            ResultSet rs = st.executeQuery(s);
            while(rs.next()){
                country_cb.addItem(rs.getString("name"));
                
            }
              country_cb.setSelectedItem("India");
            state_cb.setSelectedItem("Maharashtra");
            city_cb.setSelectedItem("Pune");
        
        } catch (SQLException ex) {
            Logger.getLogger(Add_Area.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Title_label = new javax.swing.JLabel();
        add_area_btn = new javax.swing.JButton();
        cancel_area_btn = new javax.swing.JButton();
        country_cb = new javax.swing.JComboBox<>();
        state_cb = new javax.swing.JComboBox<>();
        city_cb = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        area_text = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(850, 550));
        setMinimumSize(new java.awt.Dimension(850, 550));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setMaximumSize(new java.awt.Dimension(850, 550));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(850, 550));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(850, 550));
        jScrollPane1.setWheelScrollingEnabled(false);

        jPanel1.setInheritsPopupMenu(true);
        jPanel1.setMaximumSize(new java.awt.Dimension(845, 32767));
        jPanel1.setMinimumSize(new java.awt.Dimension(845, 547));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_wht_bg_small.PNG"))); // NOI18N

        Title_label.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        Title_label.setText("Add New Area");

        add_area_btn.setBackground(new java.awt.Color(67, 134, 250));
        add_area_btn.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        add_area_btn.setForeground(new java.awt.Color(255, 255, 255));
        add_area_btn.setText("Add");
        add_area_btn.setContentAreaFilled(false);
        add_area_btn.setMaximumSize(new java.awt.Dimension(51, 30));
        add_area_btn.setMinimumSize(new java.awt.Dimension(51, 30));
        add_area_btn.setOpaque(true);
        add_area_btn.setPreferredSize(new java.awt.Dimension(51, 30));
        add_area_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_area_btnActionPerformed(evt);
            }
        });

        cancel_area_btn.setBackground(new java.awt.Color(67, 134, 250));
        cancel_area_btn.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        cancel_area_btn.setForeground(new java.awt.Color(255, 255, 255));
        cancel_area_btn.setText("Cancel");
        cancel_area_btn.setToolTipText("");
        cancel_area_btn.setBorder(null);
        cancel_area_btn.setBorderPainted(false);
        cancel_area_btn.setContentAreaFilled(false);
        cancel_area_btn.setMaximumSize(new java.awt.Dimension(51, 25));
        cancel_area_btn.setMinimumSize(new java.awt.Dimension(51, 25));
        cancel_area_btn.setOpaque(true);
        cancel_area_btn.setPreferredSize(new java.awt.Dimension(51, 30));
        cancel_area_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_area_btnActionPerformed(evt);
            }
        });

        country_cb.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        country_cb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                country_cbItemStateChanged(evt);
            }
        });

        state_cb.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        state_cb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                state_cbItemStateChanged(evt);
            }
        });

        city_cb.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("Country");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("City");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setText("State");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setText("Area");

        area_text.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        area_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area_textActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Title_label)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(add_area_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cancel_area_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(state_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(35, 35, 35)
                                        .addComponent(country_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(city_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(area_text, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Title_label)
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(country_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(state_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(city_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(area_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_area_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancel_area_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(174, 54, 441, 390);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg.png"))); // NOI18N
        jLabel2.setText("kj");
        jLabel2.setMaximumSize(new java.awt.Dimension(850, 550));
        jLabel2.setMinimumSize(new java.awt.Dimension(850, 550));
        jLabel2.setPreferredSize(new java.awt.Dimension(850, 550));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 850, 550);

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_area_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_area_btnActionPerformed

        try
        {
                 LocalDate now = LocalDate.now();
                 Connection c=null;
                  MyConnection mo= new MyConnection(); 
                 c=mo.getMyConnection();

                Statement st = c.createStatement();
                //Query for insert into member
               String query="insert into area(area_id,city,state,country,creation_date,monitor_id,area_name)" + "VALUES(NULL,'"+city_cb.getSelectedItem().toString()+"','"+state_cb.getSelectedItem().toString()+"','"+country_cb.getSelectedItem().toString()+"',NOW(),NULL,'"+area_text.getText()+"')"; 
                //Execute query
                st.executeUpdate(query);
                System.out.println("Done");
                Component j = null;
                JOptionPane.showMessageDialog(j, "Area Added Successfully..!");
            }
            
        

        catch (Exception e)
        {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error while Adding Area..!");
        }

    }//GEN-LAST:event_add_area_btnActionPerformed

    private void cancel_area_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_area_btnActionPerformed
        dispose();
    }//GEN-LAST:event_cancel_area_btnActionPerformed

    private void country_cbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_country_cbItemStateChanged
        // TODO add your handling code here:
        if(country_cb.getSelectedItem() != null){
            try {
                String country=country_cb.getSelectedItem().toString();
                
                //Connect Database Block
                Connection c=null;
                  MyConnection mo= new MyConnection(); 
                 c=mo.getMyConnection();
                Statement st = c.createStatement();
                String s = "select * from states where country_id = (Select id from countries where name='"+country+"');";
                ResultSet rs = st.executeQuery(s);
                state_cb.removeAllItems();
                while(rs.next()){
                    state_cb.addItem(rs.getString("name"));

                }
            
            } catch (SQLException ex) {
                Logger.getLogger(Add_Area.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_country_cbItemStateChanged

    private void state_cbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_state_cbItemStateChanged
        // TODO add your handling code here:
        if(state_cb.getSelectedItem() != null){
            try {
                 
                  String state=state_cb.getSelectedItem().toString();
                 Connection c=null;
                 MyConnection mo= new MyConnection(); 
                 c=mo.getMyConnection();
                //Connect Database Block

                Statement st = c.createStatement();
                String s = "select * from cities where state_id = (Select id from states where name='"+state+"');";
                ResultSet rs = st.executeQuery(s);
                city_cb.removeAllItems();
                while(rs.next()){
                    city_cb.addItem(rs.getString("name"));

                }
            
            } catch (SQLException ex) {
                Logger.getLogger(Populate_trial.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_state_cbItemStateChanged

    private void area_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_area_textActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Area.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Area.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Area.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Area.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Area().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title_label;
    private javax.swing.JButton add_area_btn;
    private javax.swing.JTextField area_text;
    private javax.swing.JButton cancel_area_btn;
    private javax.swing.JComboBox<String> city_cb;
    private javax.swing.JComboBox<String> country_cb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> state_cb;
    // End of variables declaration//GEN-END:variables
}
