/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Testing;

import java.awt.Color;
import project.foodrive.Monitor.*;
import static java.lang.String.format;
import static java.lang.String.format;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import project.foodrive.MyConnection;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;


/**
 *
 * @author INTEL COREi3
 */
public class Add_needy_circle extends javax.swing.JFrame {

    /**
     * Creates new form Add_drive
     */
     private int validate_all=3;
     private int monitor_id=-1;
     private int area_id=-1;
     
    public Add_needy_circle() {
        initComponents();
    }
    public Add_needy_circle(int memberid,int areaid){
         initComponents();
        monitor_id=memberid;
        area_id=areaid;
    }
    
        
    private boolean check_regex(String regex,String inpuString){
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(inpuString);
        if(matcher.matches()){
            return true;
        }
        else{
            return false;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        dname_label = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Title_label = new javax.swing.JLabel();
        add_donor = new javax.swing.JButton();
        cancel_donor = new javax.swing.JButton();
        daddress_label1 = new javax.swing.JLabel();
        error_msg = new javax.swing.JLabel();
        get_addess_line = new javax.swing.JTextField();
        get_landmark = new javax.swing.JTextField();
        dname_label1 = new javax.swing.JLabel();
        get_no_of_peoples = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(850, 550));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setMaximumSize(new java.awt.Dimension(850, 550));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(850, 550));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(850, 550));
        jScrollPane1.setWheelScrollingEnabled(false);

        jPanel1.setInheritsPopupMenu(true);
        jPanel1.setMaximumSize(new java.awt.Dimension(845, 32767));
        jPanel1.setMinimumSize(new java.awt.Dimension(845, 547));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 312));

        dname_label.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        dname_label.setText("Address Line");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_wht_bg_small.PNG"))); // NOI18N

        Title_label.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        Title_label.setText("Add New Needy Circle");

        add_donor.setBackground(new java.awt.Color(67, 134, 250));
        add_donor.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        add_donor.setForeground(new java.awt.Color(255, 255, 255));
        add_donor.setText("Add");
        add_donor.setContentAreaFilled(false);
        add_donor.setMaximumSize(new java.awt.Dimension(51, 30));
        add_donor.setMinimumSize(new java.awt.Dimension(51, 30));
        add_donor.setOpaque(true);
        add_donor.setPreferredSize(new java.awt.Dimension(51, 30));
        add_donor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_donorActionPerformed(evt);
            }
        });

        cancel_donor.setBackground(new java.awt.Color(67, 134, 250));
        cancel_donor.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        cancel_donor.setForeground(new java.awt.Color(255, 255, 255));
        cancel_donor.setText("Cancel");
        cancel_donor.setToolTipText("");
        cancel_donor.setBorder(null);
        cancel_donor.setBorderPainted(false);
        cancel_donor.setContentAreaFilled(false);
        cancel_donor.setMaximumSize(new java.awt.Dimension(51, 25));
        cancel_donor.setMinimumSize(new java.awt.Dimension(51, 25));
        cancel_donor.setOpaque(true);
        cancel_donor.setPreferredSize(new java.awt.Dimension(51, 30));
        cancel_donor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_donorActionPerformed(evt);
            }
        });

        daddress_label1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        daddress_label1.setText("No.Of Peoples");

        error_msg.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        error_msg.setForeground(new java.awt.Color(204, 0, 0));

        get_addess_line.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_addess_line.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                get_addess_lineFocusLost(evt);
            }
        });
        get_addess_line.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                get_addess_lineActionPerformed(evt);
            }
        });

        get_landmark.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_landmark.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                get_landmarkFocusLost(evt);
            }
        });

        dname_label1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        dname_label1.setText("Landmark");

        get_no_of_peoples.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_no_of_peoples.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                get_no_of_peoplesFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(daddress_label1)
                                    .addComponent(dname_label, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dname_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(get_addess_line)
                                    .addComponent(get_landmark)
                                    .addComponent(get_no_of_peoples, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(error_msg, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(102, 102, 102))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(add_donor, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancel_donor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Title_label)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(2, 2, 2)
                .addComponent(Title_label)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(dname_label)
                        .addGap(19, 19, 19)
                        .addComponent(dname_label1)
                        .addGap(23, 23, 23)
                        .addComponent(daddress_label1)
                        .addGap(60, 60, 60)
                        .addComponent(error_msg))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(get_addess_line, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(get_landmark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(get_no_of_peoples, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancel_donor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add_donor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(170, 100, 500, 312);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg.png"))); // NOI18N
        jLabel2.setText("kj");
        jLabel2.setMaximumSize(new java.awt.Dimension(850, 550));
        jLabel2.setMinimumSize(new java.awt.Dimension(850, 550));
        jLabel2.setPreferredSize(new java.awt.Dimension(850, 550));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 850, 550);

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void add_donorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_donorActionPerformed
        
        if(validate_all==0)
        {
            try{
        
        
            Connection c=null;
            MyConnection mo= new MyConnection(); 
            c=mo.getMyConnection();
            System.out.println("Connected");
              
            String no_of_peoples=get_no_of_peoples.getText();
            String address_line=get_addess_line.getText();
            String landmark=get_landmark.getText();
            
            
            String query="INSERT INTO needy_circle (circle_id,no_of_peoples,address_line,landmark,area_id) " 
                    + "VALUES (NULL,?,?,?,?);";
            
            PreparedStatement pst=c.prepareStatement(query);
            
            //pst.setString(1,max_volunteers); max_volunteer NULL by Abhishek 
            pst.setInt(1,Integer.parseInt(no_of_peoples));
            pst.setString(2,address_line);
            pst.setString(3,landmark);
            pst.setInt(4,area_id);
            int ack=-1;
            System.out.println("here");
            ack =pst.executeUpdate();
            System.out.println(ack);
            JOptionPane.showMessageDialog(null, "Circle Added Successfully..!");
         }catch(Exception e){
            
             System.out.println(e);
             JOptionPane.showMessageDialog(null, e.getMessage());
         }
        }
        else{
            JOptionPane.showMessageDialog(null, "Choose correct start date!");
        }
    }//GEN-LAST:event_add_donorActionPerformed

    private void cancel_donorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_donorActionPerformed
        dispose();
    }//GEN-LAST:event_cancel_donorActionPerformed

    private void get_addess_lineFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_get_addess_lineFocusLost
        // TODO add your handling code here:
        String regex = "[a-zA-Z ]+";

        boolean isValid=check_regex(regex, get_addess_line.getText());

        if(isValid)
        {
            if(get_addess_line.getBackground().getGreen()!=253)
            {
                validate_all--;
            }
            get_addess_line.setBackground(new Color(170, 253, 197));
        }
        else{
            if(get_addess_line.getBackground().getGreen()==253)
            {
                validate_all++;
            }
            get_addess_line.setBackground(new Color(255, 186, 187));
            
        }
    }//GEN-LAST:event_get_addess_lineFocusLost

    private void get_landmarkFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_get_landmarkFocusLost
        // TODO add your handling code here:
         String regex = "[a-zA-Z ]+";

        boolean isValid=check_regex(regex, get_landmark.getText());

        if(isValid)
        {
            if(get_landmark.getBackground().getGreen()!=253)
            {
                validate_all--;
            }
            get_landmark.setBackground(new Color(170, 253, 197));
        }
        else{
            if(get_landmark.getBackground().getGreen()==253)
            {
                validate_all++;
            }
            get_landmark.setBackground(new Color(255, 186, 187));
            
        }
        
    }//GEN-LAST:event_get_landmarkFocusLost

    private void get_no_of_peoplesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_get_no_of_peoplesFocusLost
        // TODO add your handling code here:
         String regex = "\\d+";

        boolean isValid=check_regex(regex, get_no_of_peoples.getText());

        if(isValid)
        {
            if(get_no_of_peoples.getBackground().getGreen()!=253)
            {
                validate_all--;
            }
            get_no_of_peoples.setBackground(new Color(170, 253, 197));
        }
        else{
            if(get_no_of_peoples.getBackground().getGreen()==253)
            {
                validate_all++;
            }
            get_no_of_peoples.setBackground(new Color(255, 186, 187));
             
        }
    }//GEN-LAST:event_get_no_of_peoplesFocusLost

    private void get_addess_lineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get_addess_lineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_get_addess_lineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_needy_circle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_needy_circle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_needy_circle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_needy_circle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_needy_circle(35,1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title_label;
    private javax.swing.JButton add_donor;
    private javax.swing.JButton cancel_donor;
    private javax.swing.JLabel daddress_label1;
    private javax.swing.JLabel dname_label;
    private javax.swing.JLabel dname_label1;
    private javax.swing.JLabel error_msg;
    private javax.swing.JTextField get_addess_line;
    private javax.swing.JTextField get_landmark;
    private javax.swing.JTextField get_no_of_peoples;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    
}
