/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Testing;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.Timer;

/**
 *
 * @author INTEL COREi3
 */
public class trial_panel extends javax.swing.JPanel {

    JLabel pic;
    Timer tm;
    int x=0;
    String [] list= {
        "G:/projects/Foodrive/src/img/11.jpg",
        "G:/projects/Foodrive/src/img/22.jpg",
        "G:/projects/Foodrive/src/img/33.jpg",
        
        "G:/projects/Foodrive/src/img/44.jpg",
        
        "G:/projects/Foodrive/src/img/66.jpg",
        "G:/projects/Foodrive/src/img/77.jpg",
        "G:/projects/Foodrive/src/img/88.jpg"
        };
    
    
    public trial_panel() {
        
        
        initComponents();
        pic=new JLabel();
        pic.setBounds(40, 30, 490,490);
        
        setImageSize(6);
        
        tm=new Timer(2500,new ActionListener() {
            @Override 
            public void actionPerformed(ActionEvent e) {
                setImageSize(x);
                x +=1;
                if(x>=list.length){
                    x=0;
                }
            }
        });
        add(pic);
        tm.start();
        setLayout(null);
        setSize(486,488);
        
       setAlignmentX(trial_panel.LEFT_ALIGNMENT);
        setVisible(true);
        
    }
     public void setImageSize(int i){
         ImageIcon icon=new ImageIcon(list[i]);
         Image img=icon.getImage();
         Image newImg =img.getScaledInstance(pic.getWidth(),pic.getHeight(),Image.SCALE_SMOOTH);
         ImageIcon newImc = new ImageIcon(newImg);
         pic.setIcon(newImc);
         
     }
    /**
     * Creates new form trial_panel
     */
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(490, 490));
        setMinimumSize(new java.awt.Dimension(490, 490));
        setPreferredSize(new java.awt.Dimension(490, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
