/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.foodrive.Donor;

import Testing.*;
import java.awt.Component;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import project.foodrive.Monitor.Drive_RecordPanel;
import project.foodrive.MyConnection;


/**
 *
 * @author INTEL COREi3
 */
public class Donate_food_confirmation extends javax.swing.JFrame {

    /**
     * Creates new form Add_Area
     */
    private int drive_id=-1;
    private int donor_id=-1;
    private String donate_time="";
    public Donate_food_confirmation() {
        initComponents();
        
    }
    public Donate_food_confirmation(int driveid,int donorid,String donatetime) {
        initComponents();
        drive_id=driveid;
        donor_id=donorid;
        donate_time=donatetime;
        drive_text.setText(""+driveid);
        donation_time.setText(donatetime);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Title_label = new javax.swing.JLabel();
        donate_btn = new javax.swing.JButton();
        cancel_area_btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        food_quantity_text = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        drive_text = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        donation_time = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(850, 550));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setMaximumSize(new java.awt.Dimension(850, 550));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(850, 550));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(850, 550));
        jScrollPane1.setWheelScrollingEnabled(false);

        jPanel1.setInheritsPopupMenu(true);
        jPanel1.setMaximumSize(new java.awt.Dimension(845, 32767));
        jPanel1.setMinimumSize(new java.awt.Dimension(845, 547));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setMaximumSize(new java.awt.Dimension(441, 304));
        jPanel2.setMinimumSize(new java.awt.Dimension(441, 304));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_wht_bg_small.PNG"))); // NOI18N

        Title_label.setFont(new java.awt.Font("Verdana", 0, 22)); // NOI18N
        Title_label.setText("Donate Food");

        donate_btn.setBackground(new java.awt.Color(67, 134, 250));
        donate_btn.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        donate_btn.setForeground(new java.awt.Color(255, 255, 255));
        donate_btn.setText("Donate");
        donate_btn.setContentAreaFilled(false);
        donate_btn.setMaximumSize(new java.awt.Dimension(51, 30));
        donate_btn.setMinimumSize(new java.awt.Dimension(51, 30));
        donate_btn.setOpaque(true);
        donate_btn.setPreferredSize(new java.awt.Dimension(51, 30));
        donate_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donate_btnActionPerformed(evt);
            }
        });

        cancel_area_btn.setBackground(new java.awt.Color(67, 134, 250));
        cancel_area_btn.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        cancel_area_btn.setForeground(new java.awt.Color(255, 255, 255));
        cancel_area_btn.setText("Cancel");
        cancel_area_btn.setToolTipText("");
        cancel_area_btn.setBorder(null);
        cancel_area_btn.setBorderPainted(false);
        cancel_area_btn.setContentAreaFilled(false);
        cancel_area_btn.setMaximumSize(new java.awt.Dimension(51, 25));
        cancel_area_btn.setMinimumSize(new java.awt.Dimension(51, 25));
        cancel_area_btn.setOpaque(true);
        cancel_area_btn.setPreferredSize(new java.awt.Dimension(51, 30));
        cancel_area_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_area_btnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setText("Food qauntity");

        food_quantity_text.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        food_quantity_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                food_quantity_textActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setText("Drive ID");

        drive_text.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        drive_text.setEnabled(false);
        drive_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drive_textActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel7.setText("Donate Time");

        donation_time.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        donation_time.setEnabled(false);
        donation_time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donation_timeActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel8.setText("(In Number Peoples)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(donate_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cancel_area_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(drive_text, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(donation_time, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(Title_label)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                .addComponent(food_quantity_text, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(57, 57, 57))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Title_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(drive_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(donation_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(food_quantity_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(donate_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancel_area_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(210, 110, 441, 304);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg.png"))); // NOI18N
        jLabel2.setText("kj");
        jLabel2.setMaximumSize(new java.awt.Dimension(850, 550));
        jLabel2.setMinimumSize(new java.awt.Dimension(850, 550));
        jLabel2.setPreferredSize(new java.awt.Dimension(850, 550));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 850, 550);

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void donate_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donate_btnActionPerformed
        int optionSelected=JOptionPane.showConfirmDialog(null, "Are you sure?", "Warning..!", JOptionPane.YES_NO_OPTION);
        if(optionSelected==JOptionPane.YES_OPTION){
            try
            {

                    Connection c=null;
                    MyConnection mo= new MyConnection();
                    c=mo.getMyConnection();
                    int food_quantity=Integer.parseInt(food_quantity_text.getText());
                    String query="INSERT INTO collects_food_from (drive_id, donor_id, food_quantity, donation_time, donate_flag) "
                            + "VALUES(?, ?, ?, ?, 'confirm');;";

                    PreparedStatement pst=c.prepareStatement(query);
                    pst.setInt(1, drive_id);
                    pst.setInt(2, donor_id);
                    pst.setInt(3, food_quantity);
                    pst.setString(4,donate_time);
                    pst.executeUpdate();

                    query = "UPDATE drive SET status='Donor_Confirmed' WHERE drive_id=?";
                    pst=c.prepareStatement(query);
                    pst.setInt(1, drive_id);
                    pst.executeUpdate();

                    JOptionPane.showMessageDialog(null
                            , "Donation on "+donate_time+" Confirmed !");
                    this.dispose();
            }

            catch (Exception e)
            {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error while Adding Area..!");
            }
        }
    }//GEN-LAST:event_donate_btnActionPerformed

    private void cancel_area_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_area_btnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancel_area_btnActionPerformed

    private void food_quantity_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_food_quantity_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_food_quantity_textActionPerformed

    private void drive_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drive_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drive_textActionPerformed

    private void donation_timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donation_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_donation_timeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Donate_food_confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Donate_food_confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Donate_food_confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Donate_food_confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Donate_food_confirmation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title_label;
    private javax.swing.JButton cancel_area_btn;
    private javax.swing.JButton donate_btn;
    private javax.swing.JTextField donation_time;
    private javax.swing.JTextField drive_text;
    private javax.swing.JTextField food_quantity_text;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
