/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.foodrive.Donor;

import project.foodrive.Monitor.*;
import project.foodrive.Volunteer.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import project.foodrive.MyConnection;

/**
 *
 * @author INTEL COREi3
 */
public class Donor_Notification_record_panel extends javax.swing.JPanel {

    /**
     * Creates new form Notification_record_panel
     */
    private int notification_id=-1;
    public Donor_Notification_record_panel() {
        initComponents();
    }
    
    public Donor_Notification_record_panel(int notficationid) {
        initComponents();
        notification_id=notficationid;
        load_notification_detrails();
    }
    
    public void load_notification_detrails(){
         try {
            Connection c=null;
            MyConnection mo= new MyConnection();
            c=mo.getMyConnection();
            
            String query="SELECT title,description FROM notification WHERE notification_id=?"
                    + " ORDER BY indatetime DESC;";
             System.out.println(notification_id);
            PreparedStatement pst=c.prepareStatement(query);
            pst.setInt(1, notification_id);
            
            ResultSet rs=pst.executeQuery();
            
            while(rs.next()){
               title_text.setText(rs.getString("title"));
               desc_text.setText(rs.getString("description"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Notification_panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title_text = new javax.swing.JLabel();
        desc_text = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        setInheritsPopupMenu(true);
        setMaximumSize(new java.awt.Dimension(510, 70));
        setMinimumSize(new java.awt.Dimension(510, 70));
        setPreferredSize(new java.awt.Dimension(510, 70));

        title_text.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        title_text.setText("Notification Title");
        title_text.setMaximumSize(new java.awt.Dimension(400, 23));
        title_text.setMinimumSize(new java.awt.Dimension(400, 23));

        desc_text.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        desc_text.setText("Description");
        desc_text.setToolTipText("");
        desc_text.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        desc_text.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        desc_text.setMaximumSize(new java.awt.Dimension(400, 35));
        desc_text.setMinimumSize(new java.awt.Dimension(400, 35));
        desc_text.setPreferredSize(new java.awt.Dimension(400, 35));
        desc_text.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(title_text, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desc_text, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(title_text, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desc_text, javax.swing.GroupLayout.PREFERRED_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel desc_text;
    private javax.swing.JLabel title_text;
    // End of variables declaration//GEN-END:variables
}
