/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.foodrive.Donor;

import project.foodrive.Admin.*;
import Testing.*;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JPanel;
import project.foodrive.GetStarted_Final;
import project.foodrive.Monitor.Drive_status_view;
import project.foodrive.Monitor.Monitor_Notification_panel;
import project.foodrive.MyConnection;
import project.foodrive.Volunteer.Notification_panel;

/**
 *
 * @author abcd
 */
public class Donor_dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Final_start
     */
    private int donor_id=1;
    private int area_id=1;
    public Donor_dashboard() {
        initComponents();
    }
    
    public Donor_dashboard(int donorid,int areaid){
         initComponents();
        donor_id=donorid;
        area_id=areaid;
         load_details_in_header();
        
        
    }
    private Color mouseExitedColor = new Color(21, 95, 48);
    private Color mouseEnteredColor = new Color(0,23,0);
    private Color mouseClickedColor = new Color(21,143,21);
    private Color passiveFontColor = new Color(204,204,204);
    private Color activeFontColor = new Color(255,255,255);
    private int selected_option_from_left=0;
    
     private void load_details_in_header(){
        try {
            Connection c=null;
            MyConnection mo= new MyConnection();
            c=mo.getMyConnection();
            //get volunteer req count
            String query="SELECT donor_name FROM donor WHERE donor_id=?; ";
            
            PreparedStatement pst=c.prepareStatement(query);
            pst.setInt(1, donor_id);
            ResultSet rs=pst.executeQuery();
            
            if(rs.next()){
              this.donor_name_lab.setText(rs.getString("donor_name"));
            }
            
            c.close();
            //join_count.setText(""+count);
        } catch (SQLException ex) {
            Logger.getLogger(Monitor_Notification_panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void setAllOptionAsNonSelected(){
        profile_pan.setBackground(mouseExitedColor);
        volunteer_label.setForeground(passiveFontColor);
        drive_pan.setBackground(mouseExitedColor);
        donor_label.setForeground(passiveFontColor);
        notification_pan.setBackground(mouseExitedColor);
        chapter_label.setForeground(passiveFontColor);
        area_pan.setBackground(mouseExitedColor);
        monitor_label.setForeground(passiveFontColor);
        
    }
     public void load_in_main_panel(Component panel){
        main_load_donpan.removeAll();
        main_load_donpan.add(panel,BorderLayout.CENTER);
        main_load_donpan.revalidate();
        main_load_donpan.repaint();
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        logout_btn = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        donor_name_lab = new javax.swing.JLabel();
        leftPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        profile_pan = new javax.swing.JPanel();
        volunteer_label = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        drive_pan = new javax.swing.JPanel();
        donor_label = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        notification_pan = new javax.swing.JPanel();
        chapter_label = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        area_pan = new javax.swing.JPanel();
        monitor_label = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        main_load_donpan = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 600));
        setResizable(false);

        headerPanel.setBackground(new java.awt.Color(21, 95, 48));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/notification.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        logout_btn.setForeground(new java.awt.Color(255, 255, 255));
        logout_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout_small.png"))); // NOI18N
        logout_btn.setText("Logout");
        logout_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_btnMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe Marker", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Donor");

        donor_name_lab.setFont(new java.awt.Font("Segoe Marker", 0, 20)); // NOI18N
        donor_name_lab.setForeground(new java.awt.Color(255, 255, 255));
        donor_name_lab.setText("Donor Name");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(donor_name_lab, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(logout_btn)
                .addGap(24, 24, 24))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(donor_name_lab)
                            .addComponent(jLabel8)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, headerPanelLayout.createSequentialGroup()
                        .addComponent(logout_btn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap())
        );

        leftPanel.setBackground(new java.awt.Color(21, 95, 48));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_gr_bg_medium.PNG"))); // NOI18N

        profile_pan.setBackground(new java.awt.Color(21, 95, 48));
        profile_pan.setMaximumSize(new java.awt.Dimension(250, 45));
        profile_pan.setMinimumSize(new java.awt.Dimension(250, 45));
        profile_pan.setPreferredSize(new java.awt.Dimension(250, 45));
        profile_pan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profile_panMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profile_panMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profile_panMouseExited(evt);
            }
        });

        volunteer_label.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        volunteer_label.setForeground(new java.awt.Color(204, 204, 204));
        volunteer_label.setText("Profile");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/monitor_icon.png"))); // NOI18N

        javax.swing.GroupLayout profile_panLayout = new javax.swing.GroupLayout(profile_pan);
        profile_pan.setLayout(profile_panLayout);
        profile_panLayout.setHorizontalGroup(
            profile_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profile_panLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(volunteer_label)
                .addContainerGap(128, Short.MAX_VALUE))
        );
        profile_panLayout.setVerticalGroup(
            profile_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profile_panLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(profile_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(volunteer_label))
                .addContainerGap())
        );

        drive_pan.setBackground(new java.awt.Color(21, 95, 48));
        drive_pan.setMaximumSize(new java.awt.Dimension(250, 45));
        drive_pan.setMinimumSize(new java.awt.Dimension(250, 45));
        drive_pan.setPreferredSize(new java.awt.Dimension(250, 45));
        drive_pan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                drive_panMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                drive_panMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                drive_panMouseExited(evt);
            }
        });

        donor_label.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        donor_label.setForeground(new java.awt.Color(204, 204, 204));
        donor_label.setText("Drive");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/donate_icon.png"))); // NOI18N

        javax.swing.GroupLayout drive_panLayout = new javax.swing.GroupLayout(drive_pan);
        drive_pan.setLayout(drive_panLayout);
        drive_panLayout.setHorizontalGroup(
            drive_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drive_panLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(donor_label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        drive_panLayout.setVerticalGroup(
            drive_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drive_panLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(drive_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(donor_label))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        notification_pan.setBackground(new java.awt.Color(21, 95, 48));
        notification_pan.setMaximumSize(new java.awt.Dimension(250, 45));
        notification_pan.setMinimumSize(new java.awt.Dimension(250, 45));
        notification_pan.setPreferredSize(new java.awt.Dimension(250, 45));
        notification_pan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                notification_panMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                notification_panMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                notification_panMouseExited(evt);
            }
        });

        chapter_label.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        chapter_label.setForeground(new java.awt.Color(204, 204, 204));
        chapter_label.setText("Notifications");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/notification.png"))); // NOI18N

        javax.swing.GroupLayout notification_panLayout = new javax.swing.GroupLayout(notification_pan);
        notification_pan.setLayout(notification_panLayout);
        notification_panLayout.setHorizontalGroup(
            notification_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notification_panLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(chapter_label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        notification_panLayout.setVerticalGroup(
            notification_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notification_panLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(notification_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(chapter_label))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        area_pan.setBackground(new java.awt.Color(21, 95, 48));
        area_pan.setMaximumSize(new java.awt.Dimension(250, 45));
        area_pan.setMinimumSize(new java.awt.Dimension(250, 45));
        area_pan.setPreferredSize(new java.awt.Dimension(250, 45));
        area_pan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                area_panMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                area_panMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                area_panMouseExited(evt);
            }
        });

        monitor_label.setBackground(new java.awt.Color(204, 204, 204));
        monitor_label.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        monitor_label.setForeground(new java.awt.Color(204, 204, 204));
        monitor_label.setText("Area Details");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/location_icon.png"))); // NOI18N

        javax.swing.GroupLayout area_panLayout = new javax.swing.GroupLayout(area_pan);
        area_pan.setLayout(area_panLayout);
        area_panLayout.setHorizontalGroup(
            area_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(area_panLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(monitor_label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        area_panLayout.setVerticalGroup(
            area_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, area_panLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(area_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(monitor_label))
                .addContainerGap())
        );

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(notification_pan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(area_pan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(drive_pan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(profile_pan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addComponent(profile_pan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(drive_pan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(notification_pan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(area_pan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        main_load_donpan.setToolTipText("");
        main_load_donpan.setMaximumSize(new java.awt.Dimension(850, 550));
        main_load_donpan.setMinimumSize(new java.awt.Dimension(850, 550));
        main_load_donpan.setPreferredSize(new java.awt.Dimension(850, 550));
        main_load_donpan.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(main_load_donpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(main_load_donpan, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1116, 638));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void profile_panMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profile_panMouseEntered
        // TODO add your handling code here:
        if(selected_option_from_left!=1)
        {
            profile_pan.setBackground(mouseEnteredColor);
            volunteer_label.setForeground(activeFontColor);
        }
        
        
    }//GEN-LAST:event_profile_panMouseEntered

    private void drive_panMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drive_panMouseEntered
        // TODO add your handling code here:
        if(selected_option_from_left!=2)
        {
            drive_pan.setBackground(mouseEnteredColor);
            donor_label.setForeground(activeFontColor);
        }
    }//GEN-LAST:event_drive_panMouseEntered

    private void notification_panMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notification_panMouseEntered
        // TODO add your handling code here:
        if(selected_option_from_left!=3)
        {
        notification_pan.setBackground(mouseEnteredColor);
        chapter_label.setForeground(activeFontColor);
        }
        
    }//GEN-LAST:event_notification_panMouseEntered

    private void area_panMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_area_panMouseEntered
        // TODO add your handling code here:
        if(selected_option_from_left!=4)
        {
            area_pan.setBackground(mouseEnteredColor);
            monitor_label.setForeground(activeFontColor);
        }
    }//GEN-LAST:event_area_panMouseEntered

    private void profile_panMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profile_panMouseExited
        // TODO add your handling code here:
        if(selected_option_from_left!=1)
        {
            profile_pan.setBackground(mouseExitedColor);
            volunteer_label.setForeground(passiveFontColor);
        }
    }//GEN-LAST:event_profile_panMouseExited

    private void notification_panMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notification_panMouseExited
        // TODO add your handling code here:
        if(selected_option_from_left!=3)
        {
            notification_pan.setBackground(mouseExitedColor);
            chapter_label.setForeground(passiveFontColor);
        }
    }//GEN-LAST:event_notification_panMouseExited

    private void area_panMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_area_panMouseExited
        // TODO add your handling code here:
        if(selected_option_from_left!=4)
        {
            area_pan.setBackground(mouseExitedColor);
            monitor_label.setForeground(passiveFontColor);
        }
    }//GEN-LAST:event_area_panMouseExited

    private void drive_panMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drive_panMouseExited
        // TODO add your handling code here:
        if(selected_option_from_left!=2)
        {
            drive_pan.setBackground(mouseExitedColor);
            donor_label.setForeground(passiveFontColor);
        }
    }//GEN-LAST:event_drive_panMouseExited

    private void profile_panMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profile_panMouseClicked
        setAllOptionAsNonSelected();
        profile_pan.setBackground(mouseClickedColor);
        volunteer_label.setForeground(activeFontColor);
        selected_option_from_left=1;
        
        main_load_donpan.removeAll();
        main_load_donpan.add(new Donor_profile_view(donor_id),BorderLayout.CENTER);
        main_load_donpan.revalidate();
        main_load_donpan.repaint();
        
    }//GEN-LAST:event_profile_panMouseClicked

    private void drive_panMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drive_panMouseClicked
        // TODO add your handling code here:
        setAllOptionAsNonSelected();
        drive_pan.setBackground(mouseClickedColor);
        donor_label.setForeground(activeFontColor);
        selected_option_from_left=2;
        main_load_donpan.removeAll();
        main_load_donpan.add(new Donor_drive_status_view(donor_id, area_id,this),BorderLayout.CENTER);
        main_load_donpan.revalidate();
        main_load_donpan.repaint();
        
        
        
        
    }//GEN-LAST:event_drive_panMouseClicked

    private void notification_panMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notification_panMouseClicked
        // TODO add your handling code here:
        setAllOptionAsNonSelected();
        notification_pan.setBackground(mouseClickedColor);
        chapter_label.setForeground(activeFontColor);
        selected_option_from_left=3;
        
        main_load_donpan.removeAll();
        main_load_donpan.add(new Donor_Notification_panel(donor_id,area_id),BorderLayout.CENTER);
        main_load_donpan.revalidate();
        main_load_donpan.repaint();
    }//GEN-LAST:event_notification_panMouseClicked

    private void area_panMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_area_panMouseClicked
        // TODO add your handling code here:
        setAllOptionAsNonSelected();
        area_pan.setBackground(mouseClickedColor);
        monitor_label.setForeground(activeFontColor);
        selected_option_from_left=4;
        
         main_load_donpan.removeAll();
        main_load_donpan.add(new Donor_area_view(donor_id,area_id),BorderLayout.CENTER);
        main_load_donpan.revalidate();
        main_load_donpan.repaint();
        
        
    }//GEN-LAST:event_area_panMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        main_load_donpan.removeAll();
        main_load_donpan.add(new Donor_Notification_panel(donor_id,area_id),BorderLayout.CENTER);
        main_load_donpan.revalidate();
        main_load_donpan.repaint();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void logout_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_btnMouseClicked
        // TODO add your handling code here:
        GetStarted_Final getStarted_Final=new GetStarted_Final();
        getStarted_Final.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logout_btnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Donor_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Donor_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Donor_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Donor_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Donor_dashboard(1,1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel area_pan;
    private javax.swing.JLabel chapter_label;
    private javax.swing.JLabel donor_label;
    private javax.swing.JLabel donor_name_lab;
    private javax.swing.JPanel drive_pan;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JLabel logout_btn;
    private javax.swing.JPanel main_load_donpan;
    private javax.swing.JLabel monitor_label;
    private javax.swing.JPanel notification_pan;
    private javax.swing.JPanel profile_pan;
    private javax.swing.JLabel volunteer_label;
    // End of variables declaration//GEN-END:variables

    private void setColor(JPanel mainPanel) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}