/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.foodrive.Donor;

import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import project.foodrive.MyConnection;
import project.foodrive.Volunteer.Notification_panel;
import project.foodrive.Volunteer.Notification_record_panel;

/**
 *
 * @author INTEL COREi3
 */
public class Donor_profile_view extends javax.swing.JPanel {

    /**
     * Creates new form Donor_profile_view
     */
    private int donor_id=-1;
    public Donor_profile_view(){
        initComponents();
        
        
    }
    public Donor_profile_view(int donorid){
         initComponents();
        donor_id=donorid;
        load_donor();
    }
    private void load_donor(){
        
        try {
            System.out.println("here 0");
           
            Connection c=null;
            MyConnection mo= new MyConnection();
            c=mo.getMyConnection();
            System.out.println("connected");
          String query="SELECT * FROM donor WHERE donor_id=?;";

            
            PreparedStatement pst=c.prepareStatement(query);
            System.out.println(donor_id);
            pst.setInt(1,donor_id);
            ResultSet rs=pst.executeQuery();
             
            while(rs.next()){
                System.out.println("in rs");
               this.get_did.setText(""+rs.getInt("donor_id"));
               this.get_email.setText(rs.getString("email"));
               this.get_phone.setText(rs.getString("phone"));
               this.get_alt_phone.setText(rs.getString("alternate_phone"));
               this.get_type.setText(rs.getString("type")); 
               
               this.get_address.setText(rs.getString("address_line1"));
               this.get_city.setText(rs.getString("city"));
               this.get_state.setText(rs.getString("state"));
               this.get_country.setText(rs.getString("country"));
               this.get_area.setText(""+rs.getInt("area_id"));
               this.get_name.setText(rs.getString("donor_name"));
              
            }
        } catch (SQLException ex) {
            Logger.getLogger(Notification_panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profile = new javax.swing.JLabel();
        get_name = new javax.swing.JLabel();
        personal_details = new javax.swing.JPanel();
        email_label = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        get_did = new javax.swing.JLabel();
        get_type = new javax.swing.JLabel();
        get_email = new javax.swing.JLabel();
        phonne_label = new javax.swing.JLabel();
        get_phone = new javax.swing.JLabel();
        alt_phone_label = new javax.swing.JLabel();
        get_alt_phone = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        points_label = new javax.swing.JLabel();
        get_type1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        get_address = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        get_country = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        get_state = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        get_city = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        get_area = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(850, 550));
        setMinimumSize(new java.awt.Dimension(850, 550));
        setPreferredSize(new java.awt.Dimension(850, 550));

        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        profile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        get_name.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        get_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        get_name.setText("Name");
        get_name.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        personal_details.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Personal Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 14))); // NOI18N
        personal_details.setPreferredSize(new java.awt.Dimension(541, 190));

        email_label.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        email_label.setText("Email ");

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel13.setText("Type");

        get_did.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_did.setText("*email*");

        get_type.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_type.setText("*types*");

        get_email.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_email.setText("*email*");

        phonne_label.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        phonne_label.setText("Phone");

        get_phone.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_phone.setText("*phone*");

        alt_phone_label.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        alt_phone_label.setText("Alternate Phone ");

        get_alt_phone.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_alt_phone.setText("*altphone*");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setText("Donor Id");

        points_label.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        points_label.setText("Points");

        get_type1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_type1.setText("*points*");

        javax.swing.GroupLayout personal_detailsLayout = new javax.swing.GroupLayout(personal_details);
        personal_details.setLayout(personal_detailsLayout);
        personal_detailsLayout.setHorizontalGroup(
            personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personal_detailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personal_detailsLayout.createSequentialGroup()
                        .addGroup(personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alt_phone_label)
                            .addComponent(jLabel4)
                            .addComponent(email_label)
                            .addComponent(phonne_label)
                            .addComponent(jLabel13))
                        .addGroup(personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personal_detailsLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(get_phone)
                                    .addComponent(get_email)
                                    .addComponent(get_did, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(personal_detailsLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(get_alt_phone))
                            .addGroup(personal_detailsLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(get_type1)
                                    .addComponent(get_type)))))
                    .addComponent(points_label))
                .addContainerGap(307, Short.MAX_VALUE))
        );
        personal_detailsLayout.setVerticalGroup(
            personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personal_detailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personal_detailsLayout.createSequentialGroup()
                        .addComponent(get_did)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(get_email))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personal_detailsLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(email_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phonne_label)
                            .addComponent(get_phone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(alt_phone_label)
                            .addComponent(get_alt_phone))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(get_type)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personal_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(points_label)
                    .addComponent(get_type1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Address Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 14)))); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(539, 161));

        get_address.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_address.setText("Gujrath Colony");

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("Address Line ");

        get_country.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_country.setText("India");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("Country");

        get_state.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_state.setText("jLabel10");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("State");

        get_city.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_city.setText("jLabel11");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setText("City");

        get_area.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        get_area.setText("jLabel12");

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setText("Area_id");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(get_address, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(get_country, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(get_state, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(get_city, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(get_area, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(268, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(get_address))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(get_country))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(get_state))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(get_city))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(get_area))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(get_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(profile)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(personal_details, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profile)
                .addComponent(get_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(personal_details, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alt_phone_label;
    private javax.swing.JLabel email_label;
    private javax.swing.JLabel get_address;
    private javax.swing.JLabel get_alt_phone;
    private javax.swing.JLabel get_area;
    private javax.swing.JLabel get_city;
    private javax.swing.JLabel get_country;
    private javax.swing.JLabel get_did;
    private javax.swing.JLabel get_email;
    private javax.swing.JLabel get_name;
    private javax.swing.JLabel get_phone;
    private javax.swing.JLabel get_state;
    private javax.swing.JLabel get_type;
    private javax.swing.JLabel get_type1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel personal_details;
    private javax.swing.JLabel phonne_label;
    private javax.swing.JLabel points_label;
    private javax.swing.JLabel profile;
    // End of variables declaration//GEN-END:variables
}
